### ISSUE TITLE
Unable to access captive portal due to expired ssl cert

### ISSUE THREAD

**Issue by crass** [GrapheneOS/Vanadium#101]
I was attempting to connect to an unencrypted public wifi that had a captive portal ssl web page that needed to be accessed to in order to grant access to the internet. The ssl cert was one day expired and when I loaded the page in Vanadium I got an error message about the expired cert (as expected). However, there was no way to continue loading the page. In some browsers, there is an option to proceed anyway. I was able to test this on another phone with official android google chrome and ran into the same problem. So its probably not Vanadium specific, though it would be nice to continue browsing "insecurely", especially in this case where its the difference between having internet access or not.

**Comment by thestinger** [comment]
See https://expired.badssl.com/. You need to press advanced and then continue. This is available as long as there isn't HSTS, and there isn't HSTS for the standard captive portal URLs. HSTS would also block continuing due to an invalid certificate anyway.

**Comment by crass** [comment]
Hmm interesting, I did go to advanced and somehow I missed that link to proceed.
