### ISSUE TITLE
Allow custom search engine to be added

### ISSUE THREAD

**Issue by githupper** [GrapheneOS/Vanadium#103]
Would like to add in a self hosted Whoogle instance as default search engine but there is no provision to add them in Vanadium unlike Firefox

**Comment by thestinger** [comment]
That's not true. Custom search engines are supported. They need to have proper open search metadata.

**Comment by githupper** [comment]
What sort of metadata and how to add them into the list?

**Comment by thestinger** [comment]
https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by thestinger** [comment]
The search engine configuration menu will list recent search engines with proper metadata and they can be selected as the default.

**Comment by githupper** [comment]
Noted and will check on Opensearch Thanks

**Comment by csagan5** [comment]
Related: https://github.com/benbusby/whoogle-search/issues/105

**Comment by csagan5** [comment]
Some other interesting resources:
* http://dev.chromium.org/tab-to-search
* https://bugs.chromium.org/p/chromium/issues/detail?id=58801
