### ISSUE TITLE
App crashes related to upstream Webview updates?

### ISSUE THREAD

**Issue by cvsickle** [GrapheneOS/Vanadium#105]
My wife started getting some apps crashing shortly after they're opened since updating to GrapheneOS 2021.03.19.14 on her Pixel 4. Is this related to what I've been reading regarding Google's bugged release of the Android System Webview? Their solution is to update the Webview from the play store, but our Graphene installations are obviously using the Vanadium Webview. Could this be an upstream bug that we're experiencing? If so, it sounds like they've already fixed the upstream issues.

Here's Google's statement describing the issue that seems similar to what she's experiencing: [https://9to5google.com/2021/03/23/android-apps-crashing-webview/](https://9to5google.com/2021/03/23/android-apps-crashing-webview/)

**Comment by thestinger** [comment]
This isn't an issue for GrapheneOS because variations (where the bug occurred) are disabled in Vanadium. If you look at the Vanadium System WebView in Settings -> Apps & notifications with system apps enabled it probably doesn't have any data to clear away at all. If it does, clear it away.

**Comment by cyrinux** [comment]
I would like to say I got the problem. And was hoping a next release bring maybe a fixed web view. How can we help?

**Comment by thestinger** [comment]
That upstream bug doesn't impact GrapheneOS.

**Comment by thestinger** [comment]
The new version is available in the latest release of GrapheneOS. I can't see it solving whatever issues you're having though.

**Comment by cvsickle** [comment]
> The new version is available in the latest release of GrapheneOS. I can't see it solving whatever issues you're having though.

As you suggested, the update did not fix the app crashing issue I'm having on a Pixel 4. No issues with a Pixel 3, however, so I'm not sure what to think.

**Comment by cvsickle** [comment]
> Thanks for worry about us man. I find a workaround the time something magic happen. Using the web version of the app. Less bloated but less features. :-)

Can I ask what app(s) are giving you problems? For me, it's just Outlook which my wife and I use to sync to my work calendar (Google). It has always worked fin for me on my Pixel 3, and it worked fine on her Pixel 4 until the last update before this most recent one.

**Comment by cyrinux** [comment]
> > Thanks for worry about us man. I find a workaround the time something magic happen. Using the web version of the app. Less bloated but less features. :-)
> 
> Can I ask what app(s) are giving you problems? For me, it's just Outlook which my wife and I use to sync to my work calendar (Google). It has always worked fin for me on my Pixel 3, and it worked fine on her Pixel 4 until the last update before this most recent one.

Same app for me

**Comment by cyrinux** [comment]
> > Thanks for worry about us man. I find a workaround the time something magic happen. Using the web version of the app. Less bloated but less features. :-)
> 
> Can I ask what app(s) are giving you problems? For me, it's just Outlook which my wife and I use to sync to my work calendar (Google). It has always worked fin for me on my Pixel 3, and it worked fine on her Pixel 4 until the last update before this most recent one.

Is it working it you logout from the current already opened outlook session then try to reconnect? There is chance this will not work.

**Comment by cvsickle** [comment]
> 
> 
> > > Thanks for worry about us man. I find a workaround the time something magic happen. Using the web version of the app. Less bloated but less features. :-)
> > 
> > 
> > Can I ask what app(s) are giving you problems? For me, it's just Outlook which my wife and I use to sync to my work calendar (Google). It has always worked fin for me on my Pixel 3, and it worked fine on her Pixel 4 until the last update before this most recent one.
> 
> Is it working it you logout from the current already opened outlook session then try to reconnect? There is chance this will not work.

I completely uninstalled it and reinstalled it. If I try to login, it will crash back to the welcome screen, but if I leave it at the welcome screen, it will crash out of the app entirely.

**Comment by cyrinux** [comment]
> > > > Thanks for worry about us man. I find a workaround the time something magic happen. Using the web version of the app. Less bloated but less features. :-)
> > > 
> > > 
> > > Can I ask what app(s) are giving you problems? For me, it's just Outlook which my wife and I use to sync to my work calendar (Google). It has always worked fin for me on my Pixel 3, and it worked fine on her Pixel 4 until the last update before this most recent one.
> > 
> > 
> > Is it working it you logout from the current already opened outlook session then try to reconnect? There is chance this will not work.
> 
> I completely uninstalled it and reinstalled it. If I try to login, it will crash back to the welcome screen, but if I leave it at the welcome screen, it will crash out of the app entirely.

Ok so like me, i got no more idea that use the web version :-(

**Comment by thestinger** [comment]
Please reboot the device, then trigger the issue, then capture a bug report with that option at the top of developer tools and send it to @strcat:matrix.org on Matrix or email it to me. You need an app installed able to share it such an email app or Element.

Alternatively, you can capture logs with `adb logcat`. That won't provide as much information but may be enough to figure out what's going on.

Is it possible that they simply updated the app and it has a dependency on Play services? It may not be intended that it does, but it's possible they aren't testing without it. If that's the case, you should report the problem to them.

**Comment by cvsickle** [comment]
> Please reboot the device, then trigger the issue, then capture a bug report with that option at the top of developer tools and send it to @strcat:matrix.org on Matrix or email it to me. You need an app installed able to share it such an email app or Element.

I sent you an email with a link to the bug report. It was too large to send attached.

> Is it possible that they simply updated the app and it has a dependency on Play services? It may not be intended that it does, but it's possible they aren't testing without it. If that's the case, you should report the problem to them.

I don't think this could be the case, because the offending app works just fine on my Pixel 3 (Graphene), it's just the Pixel 4 (also Graphene) that's giving me problems. I just checked to make sure both phones have the same version installed and they do. Would the devs have a separate build of the app for each phone? I would think that would result in them having different build numbers, but I could be wrong.

Thank you.

**Comment by asdfzerozero** [comment]
same issue, pixel 4a with 5g, app starts and seems to work completely fine for approx 5 seconds then crashes.  outlook is running in  separate user account and not the main.  strangle, if I am fast enough I can send an email however but, relatively unusable.

**Comment by thestinger** [comment]
I haven't seen a reason to think this has to do with the WebView. There isn't going to be any progress on it without someone at least getting logs and likely debugging it. If someone that's able to build the OS and work on it isn't interested, then it's unlikely any progress will be made. I don't think it has anything to do with the WebView.

**Comment by Zanthed** [comment]
Outlook does not use WebView except for account creation and other forms of login requiring a website.

I'm not sure why WebView is being blamed here as I've tested that and it works no problems.

Since no one is deciding to give logs or anything useful for us to work with; I've gotten them myself. It's not WebView related.

```
11-29 20:07:58.686  1511  1866 E ArtManagerService: Failed to prepare profile for com.microsoft.office.outlook:/data/app/~~KU-iq-8oBEDHvkBZLvZTmw==/com.microsoft.office.outlook-fqb2RstB-1B_YnxcUQpO5Q==/base.apk

11-29 20:19:52.346 20594 20922 D SoLoader: libfb.so not found on /data/data/com.microsoft.office.outlook/lib-main
11-29 20:19:52.346 20594 20922 D SoLoader: libfb.so found on /data/app/~~KU-iq-8oBEDHvkBZLvZTmw==/com.microsoft.office.outlook-fqb2RstB-1B_YnxcUQpO5Q==/lib/arm64
11-29 20:19:52.347 20594 20922 D SoLoader: libfb.so not found on /data/data/com.microsoft.office.outlook/lib-main
11-29 20:19:52.347 20594 20922 D SoLoader: libfb.so found on /data/app/~~KU-iq-8oBEDHvkBZLvZTmw==/com.microsoft.office.outlook-fqb2RstB-1B_YnxcUQpO5Q==/lib/arm64
11-29 20:19:52.348 20594 20922 I com.microsoft.office.outlook: Thread[80,tid=20922,Native,Thread*=0xb400dbd40782c800,peer=0x157b2f68,"create_react_context"] recursive attempt to load library "/data/app/~~KU-iq-8oBEDHvkBZLvZTmw==/com.microsoft.office.outlook-fqb2RstB-1B_YnxcUQpO5Q==/lib/arm64/libfb.so"

11-29 20:16:49.025 19994 19994 E com.microsoft.office.outlook: Invalid ID 0x00000000.
11-29 20:16:49.391 19994 19994 E com.microsoft.office.outlook: Invalid ID 0x00000000.
11-29 20:16:49.637 19994 19994 E com.microsoft.office.outlook: Invalid ID 0x00000000.
11-29 20:16:49.673 19994 19994 E com.microsoft.office.outlook: Invalid ID 0x00000000.

11-29 20:16:54.601 19994 20232 E outlook.crash: App crashing with a native unhandled exception
11-29 20:16:54.616 19994 20224 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x533621014030 in tid 20224 (mqt_js), pid 19994 (.office.outlook)
```

Some warnings, possibly unrelated, show up. AVC denials:
```
11-29 20:16:48.664 19994 19994 W Zygote  : Can't access app profile directory: /data_mirror/cur_profiles/0/com.microsoft.office.outlook
11-29 20:16:48.733 19994 19994 W .office.outlook: type=1400 audit(0.0:4681): avc: denied { read } for name="u:object_r:odsign_prop:s0" dev="tmpfs" ino=10594 scontext=u:r:untrusted_app:s0:c2,c256,c512,c768 tcontext=u:object_r:odsign_prop:s0 tclass=file permissive=0 app=com.microsoft.office.outlook
11-29 20:16:48.738 19994 19994 W com.microsoft.office.outlook: ART APEX data files are untrusted.
11-29 20:16:48.736 19994 19994 W .office.outlook: type=1400 audit(0.0:4682): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot.art" dev="dm-8" ino=150 scontext=u:r:untrusted_app:s0:c2,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.microsoft.office.outlook
11-29 20:16:48.736 19994 19994 W .office.outlook: type=1400 audit(0.0:4683): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot-core-libart.art" dev="dm-8" ino=144 scontext=u:r:untrusted_app:s0:c2,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.microsoft.office.outlook
11-29 20:16:48.736 19994 19994 W .office.outlook: type=1400 audit(0.0:4684): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot-okhttp.art" dev="dm-8" ino=147 scontext=u:r:untrusted_app:s0:c2,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.microsoft.office.outlook
11-29 20:16:48.739 19994 19994 W .office.outlook: type=1400 audit(0.0:4685): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot-bouncycastle.art" dev="dm-8" ino=141 scontext=u:r:untrusted_app:s0:c2,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.microsoft.office.outlook
```

**Comment by grantbrown** [comment]
Commenting just to say that I can provide a second full crash log if anyone has the interest and bandwidth to resurrect this issue wherever it actually belongs. It looks broadly similar to what @Zanthed posted above, though there's nothing about ArtManagerService. The lines with "outlook.crash" are:

```
12-30 18:05:48.877 10117  5394  6440 E outlook.crash: App crashing with a native unhandled exception
12-30 18:05:49.006  1000  1464  3962 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10117/5394, android.os.BinderProxy@e7283bf)
...
12-30 18:05:34.262 10110  5700  5759 W libc    : Access denied finding property "qemu.sf.lcd_density"
12-30 18:05:34.262 10110  5700  5759 W libc    : Access denied finding property "qemu.sf.lcd_density"
12-30 18:05:34.262 10117  5394  5515 V AppCenter: {"logs":[{"type":"errorAttachment","timestamp":"2021-12-31T00:05:33.400Z","device":{"sdkName":"appcenter.android","sdkVersion":"4.3.1","model":"Pixel 5a","oemName":"Google","osName":"Android","osVersion":"12","osBuild":"SQ1A.211205.008","osApiLevel":31,"locale":"en_US","timeZoneOffset":-360,"screenSize":"1080x2138","appVersion":"4.2147.4","carrierCountry":"us","appBuild":"42147815","appNamespace":"com.microsoft.office.outlook"},"id":"f603cbd9-7c57-485e-a749-dccb78885bb4","errorId":"85ad614f-beef-4a02-8985-7f55cb221b57","contentType":"text\\/plain","fileName":"outlook_crash_log_attachment.description","data":"(giant alphanumeric string omitted)"
12-30 18:05:34.267 10093  2157  2477 D PeopleSpaceWidgetMgr: Sbn doesn't contain valid PeopleTileKey: null/0/com.google.android.gms
```

**Comment by thestinger** [comment]
Someone is going to need to debug this by building the OS with features like hardened_malloc disabled and narrowing down the cause. It's almost certainly an app bug caused by an issue like memory corruption. It ultimately needs to be fixed by the app. We could potentially add a conditional check for the app id and disable the relevant hardening feature if it's uncovered by one of the optional hardened_malloc features like zero-on-free. If no one is going to put in the work then it's not going to get resolved. The core developers don't have time available to look into bugs in third party apps.

**Comment by Jefferderp** [comment]
For those who found their way here while trying to fix Outlook crashing:

I've successfully worked around the issue by downgrading to Outlook [v4.2123.2](https://www.apkmirror.com/apk/microsoft-corporation/outlook/outlook-4-2123-2-release/microsoft-outlook-secure-email-calendars-files-4-2123-2-2-android-apk-download/).

When upgrading Outlook version-by-version, I isolated the crashing issue to version [v4.2124](https://www.apkmirror.com/apk/microsoft-corporation/outlook/outlook-4-2124-0-release/microsoft-outlook-secure-email-calendars-files-4-2124-0-2-android-apk-download/) and later.

In case it's of relevance, my steps to successfully setup Outlook v4.2123.2 were:

1) Another Microsoft app (Teams, OneDrive) already installed and *logged in* (an account is logged in and registered in system settings).
2) Outlook is installed _from scratch_, and not _updated_, i.e. no user data was present.
3) Upon installing Outlook v4.2123.2 and clicking 'Add account', the Outlook app already saw an account registered on my device, which I was able to select and proceed with, without being prompted for a password.

I hope this helps somebody!

**Comment by mailtodelete** [comment]
>

> In case it's of relevance, my steps to successfully setup Outlook v4.2123.2 were:
> 
> 1. Another Microsoft app (in my case, OneDrive) already installed and _logged in_ (my OneDrive account is visible in system settings, under _Passwords & Accounts)._
> 2. Outlook is installed _from scratch_, and not _updated_ from an earlier version. Therefore, no user data is present. I installed via ADB.
> 3. Upon installing Outlook v4.2123.2 and clicking 'Add account', the Outlook app already saw an account registered on my device, which I was able to select and proceed with, without being prompted for a password.

Unfortunately, I do not have any other microsoft services I can log into as described above. So far, I have not been able to find a version that does not exhibit the same problem (crash and restart after a handful of seconds).
