### ISSUE TITLE
Vanadium name dissepearing

### ISSUE THREAD

**Issue by helloworldkk87** [GrapheneOS/Vanadium#106]
On Pixel4a when I have my Vanadium on home screen, I long press it and click the incognito mode the text Vanadium dissepears from my home screen. Not a big deal just an fyi

**Comment by helloworldkk87** [comment]
![signal-2021-04-06-182046](https://user-images.githubusercontent.com/81927650/113735388-e2765000-9704-11eb-8fdc-4b397ac6d76f.jpg)

**Comment by thestinger** [comment]
Can't reproduce this problem. Are you using the standard launcher?

**Comment by helloworldkk87** [comment]
Yes I am. Rebooting device will fix this.. Not really any other info I could provide

**Comment by Randomeruis** [comment]
Just noticed that this applys to all apps if trying to use their homescreen widgets. Nothing to do with Vanadium.

**Comment by thestinger** [comment]
Should be filed as an OS issue then.
