### ISSUE TITLE
Vanadium does not delete all browser data

### ISSUE THREAD

**Issue by mrtootoo** [GrapheneOS/Vanadium#107]
I go to “Settings/Privacy & Security/Clear Browsing Data”.
I select ADVANCED, select all items in menu except “Saved passwords” and select “Clear data”.  
I am presented a menu “Also clear data from these sites? These sites seem important to you:“.
I select all sites (I do not have a saved password for any of these sites) and tap “Clear”.
I go back and select “Clear Browsing Data” again and I am presented a menu “Also clear data from these sites? These sites seem important to you:“ which list the same sites which I thought I just cleared from my history.  So it appears to me, Vanadium is retaining browser data even though a request is made to remove it.

**Comment by thestinger** [comment]
That's not accurate. You probably have them bookmarked so it retains their favicons.
