### ISSUE TITLE
Location with Vanadium/Bromite

### ISSUE THREAD

**Issue by fieryflamon** [GrapheneOS/Vanadium#108]
Unable to get location in vanadium/bromite, but it is available on fennec.

Using latest GOS on pixel4a.

**Comment by csagan5** [comment]
On Bromite works fine using https://www.w3schools.com/html/html5_geolocation.asp

**Comment by thestinger** [comment]
@csagan5  Can you try on a secondary user?

**Comment by csagan5** [comment]
On Android 9 and 11 it works, also tried with: https://browserleaks.com/geo (both in incognito and without)

What errors do you see in the Javascript console of Vanadium

**Comment by Zanthed** [comment]
Assumed to be fixed because of no user response in over a year.
