### ISSUE TITLE
[Request] duckduckgo html

### ISSUE THREAD

**Issue by svdm-artix** [GrapheneOS/Vanadium#111]
Right now it's not possible to add ddg HTML to the search engine list, this is very frustrating for users with js disabled by default.

**Comment by thestinger** [comment]
Why can't you add it? You can add custom search engines.

**Comment by flawedworld** [comment]
It seems that https://html.duckduckgo.com does not implement OpenSearch which is likely the cause of it not being picked up by Vanadium.

**Comment by thestinger** [comment]
You should ask them to add support for open search. It would be possible for us to hard-wire it as one of the search engine options but ideally they would support using it in browsers not doing that.

**Comment by thestinger** [comment]
Not planned. They should do it on their end.
