### ISSUE TITLE
Add support for custom search engine

### ISSUE THREAD

**Issue by hellyeahmfs** [GrapheneOS/Vanadium#113]
Please add support for custom search engine where user can add any other search engine he/she likes.
Thank you !

**Comment by thestinger** [comment]
There's support for custom search engines as long as they have Open Search metadata. You need to visit/use the search engine and then go to the search engine configuration to add it. If the option to add it is missing, it's due to them missing properly configured Open Search metadata.

**Comment by thestinger** [comment]
It uses the Open Search metadata to add it in a way that is able to integrate it for suggestions, image search and other supported features so you need to use it before it shows up.

**Comment by hellyeahmfs** [comment]
Thanks! Its working 🤠
