### ISSUE TITLE
Reddit: Videos embedded from redgifs.com do not play

### ISSUE THREAD

**Issue by yaomtc** [GrapheneOS/Vanadium#114]
For examples, see this page (desktop site required) - (NSFW) https://www.reddit.com/domain/redgifs.com
View the comments on  any of those submissions to see where it would be embedded. Instead it is a blank space, both in the desktop site and the mobile site.

On Firefox for Android, the videos play embedded.

**Comment by thestinger** [comment]
This is due to third party cookies being blocked by default.

**Comment by thestinger** [comment]
That will become the default in Chrome / Chromium too in the next couple of years. Sites should be working fine without third party cookies enabled already especially due to how that's defined.
