### ISSUE TITLE
Consider adding FLAG_SECURE and maybe TouchesWhenObscured

### ISSUE THREAD

**Issue by yodaforces** [GrapheneOS/Vanadium#115]
To prevent screenshots and Tapjacking attacks. Could also be optional via a toggle button.

More details can be found here in the Security section: https://developer.android.com/reference/android/view/View

FLAG_SECURE: https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE

Source: https://cure53.de/pentest-report_mullvad_2020_v2.pdf

**Comment by thestinger** [comment]
It is used for Incognito mode to avoid persistent screenshots / thumbnails. I don't see a reason to use this elsewhere. It would just be annoying, and it's already annoying to be unable to take screenshots of Incognito intentionally. Not having FLAG_SECURE isn't a security flaw.
