### ISSUE TITLE
Add adaptive icon support

### ISSUE THREAD

**Issue by svdm-artix** [GrapheneOS/Vanadium#116]
https://user-images.githubusercontent.com/37311915/40754866-7eb56f24-6449-11e8-9d47-94df8bc1cff2.png

This is an example of adaptive icons.
Currently the icon is the vanadium icon with a lot of white space when you change the icon shape to rounded rectangle

**Comment by sebastien46** [comment]
Seems to be implemented now using P7 on A13.
