### ISSUE TITLE
Videos on specific sites fail to play like they used to before

### ISSUE THREAD

**Issue by Technerder** [GrapheneOS/Vanadium#125]
Vanadium Version: 94.0.4606.61
OS Information: Android 11; Pixel 2 Build/RQ3A.210905.001

Like the title suggests, video's don't always seem to load on sites browsed viewed through Vanadium but work without any issues on other browsers such as DuckDuckGo. IIRC this wasn't an issue a few months ago but I can't recall the exact version where I started experiencing these issues.

YouTube - Video's work without any issues
Twitch - Fails with "An error occurred while trying to play this content. 
Twitter - Fails with "The media could not be played". (occasionally loads the first few frames of videos)

![image](https://user-images.githubusercontent.com/15988124/137770172-1da67135-903e-46c2-9e6b-23ca8143609c.png)
![image](https://user-images.githubusercontent.com/15988124/137770183-dec0d968-8b49-469e-a3cc-b55d84346631.png)

**Comment by csagan5** [comment]
Is there a specific error in the console logs? Could this be related to Vulkan? `chrome://gpu` should tell about hw acceleration and related settings

**Comment by thestinger** [comment]
@Technerder 

Is this still an issue for you?
