### ISSUE TITLE
Auto-fill box (like for username) covers keyboard & "choose input method"

### ISSUE THREAD

**Issue by yaomtc** [GrapheneOS/Vanadium#130]
Auto-fill box (like for username) appears on a layer above the keyboard & the "choose input method" box. I don't see a way to dismiss this autofill box, and it can make it impossible to see the input method choices if I push the button to bring it up while enough autofill suggestions are on the screen. I don't think this is intended behavior, and I would think this is probably an upstream thing?

**Comment by Zanthed** [comment]
If you're using an accessibility service for auto-fill, then that's not something we can fix.

**Comment by yaomtc** [comment]
You are misunderstanding me. This is when _Vanadium_ has something saved (how do I disable this? I never use Vanadium's saved field entries) and I'm trying to change the keyboard to KeePassDX.

**Comment by Zanthed** [comment]
Post a screenshot please.

**Comment by yaomtc** [comment]
I would, but my phone is currently out of commission for a failed screen replacement. Hopefully I will have it back up and running on Monday when I can get a professional to take a look at it.

I can tell you what I remember, though. I would tap the username field for a login, and a box appears beneath the username field with yaomtc and one other suggestion. This box should not float up above the language/keyboard switching dialogue, but it does.

**Comment by yaomtc** [comment]
![Screenshot_20220407-230436](https://user-images.githubusercontent.com/5534045/162354945-d88b819b-5e7b-4e24-9ea0-7ec64225b243.png)
