### ISSUE TITLE
GrapheneOS Keyboard Support

### ISSUE THREAD

**Issue by enyaw-wang** [GrapheneOS/Vanadium#134]
Hi, I understand this is the wrong section to post an issue like mine but I couldn't find any section for keyboard support. I am currently struggling to change the language to Chinese on my board despite activating it in the systems menu. Is this something you guys can check out?
Thanks for building such a beautiful OS

Wayne

**Comment by thestinger** [comment]
It's not one of the supported languages. You need to install a keyboard with support for it.
