### ISSUE TITLE
XS-Leaks in Vanadium

### ISSUE THREAD

**Issue by git70** [GrapheneOS/Vanadium#136]
Hi
I checked XS-Leak leaks on the website https://xsinator.com
The test showed 21 of 38 problems
Can you fix them at Vanadium level or only in Chromium?

Context:
https://www.bleepingcomputer.com/news/security/researchers-discover-14-new-data-stealing-web-browser-attacks/
and
https://xsinator.com/paper.pdf

Best Regards!

**Comment by flawedworld** [comment]
The issues described here are architectural browser flaws which would need upstream resolution, it's not realistic for downstream chromium derivatives to reasonably fix them.
