### ISSUE TITLE
Unable to Create Cookie Exceptions for Cookies Stored at https Addresses

### ISSUE THREAD

**Issue by MetalNeo** [GrapheneOS/Vanadium#137]
Users are unable to create a cookie exception for sites that use `:` in the URL field. This limitation means that Vanadium can only create cookie exceptions for URLs such as `github.com` instead of `https://github.com`.

Some cookies are explicitly stored using the URL starting with `https://` and will not persist if an exception is made for the base URL.

**Comment by flawedworld** [comment]
This is an upstream chromium bug. Confirmed on Chrome 96.0.4664.104

**Comment by csagan5** [comment]
@uazo FYI

**Comment by MetalNeo** [comment]
Not sure when it was changed, but upstream seems to have fixed this issue. You still can't explicitly specify `https://` addresses, but they are included when you make an exception for the base URL.

Closing issue.
