### ISSUE TITLE
Play Controls on Lock Screen for Vanadium Don't Work

### ISSUE THREAD

**Issue by nullagit** [GrapheneOS/Vanadium#143]
**Vanadium Version**: 96.0.4664.104 / 97.0.4692.70
**Operating system**: Android 12 (GrapheneOS); Pixel 4 Build/SQ1A.211205.008 & SQ1A.220105.002

**Summary**: When I play a video in Vanadium from any number of video sites, lock my screen, and then press the play button/arrow on the lock screen, the video (audio) doesn't play. Unlocked with Vanadium focused, the audio/video plays.

**Steps to Reproduce**: 
1. Visit your favorite video site (Youtube, Brighteon, Rumble, D.Tube, Twitch, etc) and play a video. 
2. Let the video play for a few seconds to confirm it's loaded and playing correctly. 
3. Press the power button to lock the screen (the audio/video stops).
4. Tap the screen to wake it up and reveal the Vanadium media player controls (phone is still locked).
5. Press the play arrow button to play the video. Notice the play arrow briefly turns to a pause icon, then back to a play arrow. 
6. The video/audio never plays. 

**What I've Tried to Resolve**:
1. Disabling hardware acceleration, enabling hardware acceleration
2. Set DRM content allowed
3. Battery usage set to "Unrestricted" in App settings
4. Background data enabled, Unrestricted data usage enabled
5. I tried Bromite, which works as expected, but only for a few minutes before the video/audio eventually stops. 
6. Upgrade to the latest Beta version of GrapheneOS.

**Comment by thestinger** [comment]
This already seems to be reported at https://github.com/GrapheneOS/Vanadium/issues/138.
