### ISSUE TITLE
The accept-language header is set automatically

### ISSUE THREAD

**Issue by nadrad** [GrapheneOS/Vanadium#144]
It seems like the accept-language header in Vanadium is set automatically based on the keyboard layouts on the phone. It doesn't seem like a good idea because it reveals extra information and makes the device more unique.

**Comment by jpds** [comment]
Looking at my own HTTPd logs - this behaviour changed around the 10th this month and now only the first language set is sent.

Possibly related to https://github.com/GrapheneOS/Vanadium/blob/c890668e377ae1d0970c136d0c94e585fe704d76/patches/0079-Disable-detailed-language-settings-by-default.patch ?

**Comment by thestinger** [comment]
This seems fine already. Feature requests for overriding the default time zone, language, etc. can be filed separately but it won't be a priority.

**Comment by jpds** [comment]
Strangely, this reverted back to the old behavior of showing all the languages set since the 2023012500 update.

**Comment by thestinger** [comment]
The feature flag might have expired.
