### ISSUE TITLE
Open links in incognito always (same as Bromite)

### ISSUE THREAD

**Issue by githupper** [GrapheneOS/Vanadium#147]
Many paywall sites like Business Insider tracks user on how many articles they read and block them using cookies to track the user. 
Would like to have this functionality added, which is currently in Bromite, to be on Vanadium browser as well to ensure not just paywall sites but to prevent other sites from tracking Vanadium users as well.

**Comment by Zanthed** [comment]
#65

**Comment by githupper** [comment]
Noted. Will close it. Thanks
