### ISSUE TITLE
Add support for search engine options available in desktop chromium

### ISSUE THREAD

**Issue by tiklii** [GrapheneOS/Vanadium#148]
Which includes:

- Ability to add custom search engine and
- Tab/Space to search (or some other convenient way for mobile devices, but I think 'space to search' works)

So, this is a feature I don't understand why it is omitted in chromium android in the first place. It is a neat little convenience and shouldn't be hard to implement (correct me if I am wrong). Here are some possible use cases:
 
- you can add search engines not implementing OpenSearch.
- you can add search engines following OpenSearch but with custom queries. For example, you can search in " 'Books', 'Fiction', 'German' " on some torrent tracker. You can order them according to date, comments, downloads etc.
- it saves time and clicks. I don't have to go on a website, click on the menu to show the search bar, select three categories and make the search. Instead I would type a small keyword in search bar, press space and would make the search.
- I use duckduckgohtml as my default search engine on desktop simply because its noticeably faster than regular ddgo for me (I don't like the ui of ddgolite; also google is similarly fast but I don't want to use it as my default). But ddgolite doesn't support images, so I have short keywords associated 'di' and 'gi' associated with image search on ddgo and google.

**Comment by thestinger** [comment]
This doesn't fit within the scope of Vanadium and needs to be implemented in Chromium upstream. It would be far too difficult for us to maintain this and it would be a drain on the resources needed to work on privacy and security improvements which are already spread far too thin.
