### ISSUE TITLE
avoid triggering warning about Play Services not being present (regression from earlier)

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Vanadium#15]

**Comment by csagan5** [comment]
Related: https://github.com/bromite/bromite/issues/281

**Comment by Zoraver** [comment]
I stripped down https://1.1.1.1/help to 15 lines that still triggers the notification (https://gist.github.com/Zoraver/c3ef92cee4dae9cd932317e4a22b2427). The cloudflare script expands the `<stream>` tag to a bunch of nested `<div>` tags which contains a `<video>` tag. I then created an html file that has the following body:

```
<body>
    <main>
        <video controls>
            <source src="video.mp4" type="video/mp4">
        </video>
    </main>
</body>
```

which also triggers the notification. It seems that the `<video>` tag is what triggers the notification. My current guess is that it has something to do with Chromecast integration.

**Comment by thestinger** [comment]
@Zoraver Thanks for investigating this. I've resolved it with https://github.com/GrapheneOS/Vanadium/blob/9bb898ebcee8102fd60da961ee17c458eaf3ec7f/0020-disable-media-router-media-remoting-by-default.patch and https://github.com/GrapheneOS/Vanadium/blob/9bb898ebcee8102fd60da961ee17c458eaf3ec7f/0021-disable-media-router-by-default.patch. It's possible that only the 2nd patch is needed, but I'd rather just disable both settings and I don't feel like narrowing down which one resolved the issue.

**Comment by csagan5** [comment]
@thestinger I am going to try these patches and possibly include them in Bromite.
