### ISSUE TITLE
Copying URLs from the address bar into text fields on another site doesn't work

### ISSUE THREAD

**Issue by TheMCNerd2017** [GrapheneOS/Vanadium#156]
Copying a URL from the address bar with the copy button and attempting to paste it into a text field on a site does not work anymore. Nothing is actually pasted into the text field. If I copy the URL manually (by pressing the edit button and selecting the full URL) it works correctly. Additionally, copying a URL from the address bar with the copy button and pasting the URL into other programs works correctly.

Vanadium: 98.0.4758.87
Operating System: GrapheneOS 12 (SQ1A.220205.002.2022020800)
Device: Pixel 4 XL

**Comment by Zanthed** [comment]
Don't think this is an issue anymore based on my testing with Vanadium 100.

Please confirm if this is still an issue or not.

**Comment by TheMCNerd2017** [comment]
> Don't think this is an issue anymore based on my testing with Vanadium 100.
> 
> Please confirm if this is still an issue or not.

Sorry for the very late reply (I don't check my email often) but the issue is indeed fixed with Vanadium 100.
