### ISSUE TITLE
Shortcuts on new tab no longer appearing

### ISSUE THREAD

**Issue by yaomtc** [GrapheneOS/Vanadium#160]
I am in the Beta channel for GrapheneOS. Ever since an update last night or this morning, my shortcuts have been missing from the new tab page of Vanadium, which is on version 99.0.4844.48. 

I have tried enabling and disabling the homepage (what is "Vanadium's homepage" anyway?), which does nothing and I'm not sure that's relevant, but it's the best guess I had from what's available in Settings. Also, my History is still there, it hasn't been cleared recently.

![Screenshot_20220303-161608](https://user-images.githubusercontent.com/5534045/156654395-d0962a03-a63f-43e6-9de9-6456b9bf9d78.png)

**Comment by thestinger** [comment]
This is the UI for Chromium 99.

**Comment by thestinger** [comment]
Vanadium has been upgraded to Chromium 99. It's possible we need to adjust our changes to the new tab page.

**Comment by TheMCNerd2017** [comment]
I didn't know this was a bug (I actually thought it was a feature). I personally prefer the New Tab page being empty and it would be cool if this was added as an option.

**Comment by thestinger** [comment]
We're intentionally disabling suggested articles and the new version of the page. It's not intended that there are no commonly used sites listed at all.

**Comment by TheMCNerd2017** [comment]
> We're intentionally disabling suggested articles and the new version of the page. It's not intended that there are no commonly used sites listed at all.

Yeah I'm aware it wasn't intended for the commonly used sites to not show up at all.

**Comment by uazo** [comment]
> I didn't know this was a bug (I actually thought it was a feature).

I found a similar problem too, fixed with https://github.com/uazo/bromite/commit/f8940a633976f7c688dec6cd5efc75fc33efb84f
maybe it can help you

**Comment by quh4gko8** [comment]
> 

It did help fix the missing new tab feed, thanks @uazo
