### ISSUE TITLE
Manually set Search Engine

### ISSUE THREAD

**Issue by evasiv** [GrapheneOS/Vanadium#164]
There are currently 5 options for the default search engines with no option to manually set a different one.

It would be great to have the option to set the default manually or add additional search engines.

**Comment by thestinger** [comment]
You can already do that. Visit the search engine, use it, then add it in the menu. It needs to have open search metadata.

**Comment by evasiv** [comment]
Add it in what menu?   I tried setting Brave search as the default, Google sucks and honestly surprised it's even an option in a degoogled environment.

**Comment by Zanthed** [comment]
@evasiv Settings -> Search engine

**Comment by evasiv** [comment]
I got it. I don't know why that was so hard. 🤦

**Comment by Zanthed** [comment]
It's the exact same process as on all other Android Chromium browsers.

**Comment by thestinger** [comment]
> Google sucks and honestly surprised it's even an option in a degoogled environment

You're misunderstanding GrapheneOS. It's based on AOSP which does not have Google apps and services. The purpose of the project is providing a private and secure mobile OS. It doesn't exist to remove Google apps or services as an option and it's not clear why you think we would/should remove Google as a search engine option in our browser. We obviously won't build those kinds of apps and services into the OS or give them any kind of special privileges but we do not take actions specifically against any service provider and it would make no sense. Google apps and services can be installed and used on GrapheneOS. That's the whole point of https://grapheneos.org/usage#sandboxed-google-play. I suggest reading https://grapheneos.org/features to understand the project project.
