### ISSUE TITLE
Option to export bookmarks/current tabs

### ISSUE THREAD

**Issue by Technerder** [GrapheneOS/Vanadium#168]
Is there an option/feature within Vanadium that would allow someone to easily export bookmarks or the currently opened tabs to a flat file for backup purposes?

**Comment by akc3n** [comment]
No, there is not.
Close as this is a Duplicate #102.

**Comment by Zanthed** [comment]
Tracked at https://github.com/GrapheneOS/Vanadium/issues/102 and https://github.com/GrapheneOS/Vanadium/issues/149 already

**Comment by alurm** [comment]
Perhaps I misunderstood something, but I want to state that it's currently possible to select all open tabs and «share» them. A file with a numbered list of links will be shared to an application.

I don't see a way to import or bookmark that list, but that's a different issue.

Initially when I read «no, there is not» I got an impression that there was no such feature, but there is.

Thanks for Vanadium and Graphene :)

**Comment by Yolakalemowa** [comment]
> That's true, there already is a way to import open tabs.

Hi is there a way to share inactive tabs?
