### ISSUE TITLE
MediaDevices fingerprinting

### ISSUE THREAD

**Issue by TheFireKahuna** [GrapheneOS/Vanadium#172]
On GrapheneOS, Pixel 6 Pro, latest version (as off April 22nd) Vanadium leaks a completely unique fingerprint for the media devices (hardware) reported. On AmIUnique its the sole truly unique fingerprint of the browser, everything else is sub 0.01% or higher (even Canvas unlike Bromite surprisingly). 

An option to enable known mitigations for this would fix a major leak in privacy for GrapheneOS users.

**Comment by thestinger** [comment]
Does not appear to be an issue anymore.
