### ISSUE TITLE
wfm-connect header not accepted in webview

### ISSUE THREAD

**Issue by mpelley92** [GrapheneOS/Vanadium#173]
![Screenshot_20220424-003157](https://user-images.githubusercontent.com/47612684/164959915-6ce85e0c-8a60-4c4a-a8bb-e363bbc41993.png)

The Walmart schedule app requires the redirect be handled by the webview application. Stock android webview has no issue handling this request. Developers of the schedule app says the webview developer has to implement the ability for the webview application to redirect based on the URL scheme.

Please advise if this is something I can bypass or if a future update can add this ability.

Thank you.

**Comment by thestinger** [comment]
Vanadium is based on Chromium and provides a WebView based on the standard one. The developers of this app appear to be mistaken about how things work.

**Comment by thestinger** [comment]
No such thing as wfm-connect in all of Chromium.

**Comment by thestinger** [comment]
In all likelihood, this application is broken with Android 12, not GrapheneOS specifically. Unless you've tried on the stock Pixel OS on Android 12 and it works there, that's probably the issue. "Stock Android" is not a specific OS. The stock OS on a Pixel 5 is not at all the same OS as a Galaxy S10, and GrapheneOS is much closer to the stock OS on a Pixel than most vendor Android variants.

**Comment by mpelley92** [comment]
Thank you for the quick reply. By stock OS I do mean the variant of Android 12 that is installed on the Google Pixel 4a 5G. The app worked normal before changing to GrapheneOS.

I'm not a fan of the app, nor does it seem the "support team" that the company tells me to contact is either bit knowledgeable about the issue.

Again, I appreciate the quick response. I will be forced to use the app on an old outdated phone until they release an update that works the way it should.
