### ISSUE TITLE
PWA WebAPK support

### ISSUE THREAD

**Issue by ein-bandit** [GrapheneOS/Vanadium#179]
Hello,

Update: This is probably a feature request. 
It is all about the so-called [WebAPK](https://web.dev/webapks/)
It looks like this is currently only supported in Chrome.
As I have seen the generated apk and Chrome share data (cookies, web storage, etc), so this feature may not be possible in a security hardened environment like GrapheneOS. Is this assumption correct?

------------ Initial Request
I have troubles with installing PWAs to my phone.
Vanadium shows the "install app" menu item, so the PWA is correctly recognized. Alternatively Vanadium shows the default install prompt, all fine.
But when installing a PWA it actually never gets registered in the system, not findable inside the app drawer or apps list in settings.
It looks like it is only "Add to homescreen" functionality, but not a "real pwa install". 

I verified it is not an issue with the respective PWA by using multiple different PWAs and verified the web apps by installing it via chrome (on other devices w/ play services though). 

Sadly I was unable to find a vanadium apk to test it on the other devices and building from source is not suitable for me. 

Does work on: Chrome (Android 12)
Does not work on: Bromite, Vanadium, Chromium, Firefox (all Stock Android 12 and Graphene OS) 

I was not 100% sure where to open this issue because it may also be GrapheneOS related.

Pixel 4a
Graphene OS (latest) / Android 12

**Comment by flawedworld** [comment]
I don't think this will be feasible unless the chromium team make an approach which can be used by us and 3rd party vendors.

**Comment by D3V1LC0D3R** [comment]
@flawedworld cant one use this shell_apk? What exactly is missing here? https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/android/webapk

**Comment by flawedworld** [comment]
The generation is done on a remote server rather than on device in Chrome, we would want this to be done fully on-device in GrapheneOS.
