### ISSUE TITLE
Hardcode WebRTC device_id_salt for built in hardware on GrapheneOS devices

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/Vanadium#181]
This would make all GrapheneOS users blend in better with each other, but I don't see a good way to deal with this on 3rd party devices beyond continuing what chromium is currently doing (Randomising on first launch), it needs some brainstorming, but doing this might make sense.

**Comment by thestinger** [comment]
Doesn't seem like an issue. They're per-origin, randomized and get cleared by deleting site data.

**Comment by thestinger** [comment]
Does not seem like an issue. They have randomized ids that are reset on clearing data for a site.
