### ISSUE TITLE
Vanadium ANR on some website

### ISSUE THREAD

**Issue by thelittlefireman** [GrapheneOS/Vanadium#185]
Hi,
Vanadium freeze everytime i go to: [https://xpenology.com/forum/](https://xpenology.com/forum/) on a pixel 6 pro. My device is uptodate.

Thanks

**Comment by thelittlefireman** [comment]
I've sent some logcat to contact@grapheneos.org when vanadium crash.
My pixel 6 pro is :
Build SP2A.220505.002.2022051100
Vanadium 101.0.4951.61

**Comment by thelittlefireman** [comment]
I made some tests: 
 - with bitwarden autofill service enable in accessibility service is enable vanadium is ANR
 - when i disable it, vanadium does not freeze

**Comment by thestinger** [comment]
This sounds like a Bitwarden issue. An accessibility service is fully capable of breaking apps.

**Comment by thestinger** [comment]
Does it happen with other browsers like Bromite and Chrome?

**Comment by akc3n** [comment]
@thelittlefireman 

> > with bitwarden autofill service enable in accessibility service 

With regards to accessibility services specific to password managers

> accessibility services and device managers are very dangerous
> you really shouldn't use accessibility services unless you have a disability requiring one, it's not an appropriate way to implement something like a password manager rather than using the autofill service (ideally) or at least a custom keyboard (for apps not supporting autofill services)

[Permalink to log entry](https://freenode.logbot.info/grapheneos/20210318#c7298771)

**Comment by thelittlefireman** [comment]
> Does it happen with other browsers like Bromite and Chrome?

I'm unable to install chrome from play store, i dont known why. I try with firefox and it doesn't freeze.

**Comment by thestinger** [comment]
Trying Firefox isn't help since it's not Chromium-based.

**Comment by thelittlefireman** [comment]
> Trying Firefox isn't helpful since it's not Chromium-based.

I try with brave browser and i dont get freeze.
