### ISSUE TITLE
Upon updating to the latest version, I was signed out of every site that I was signed in to

### ISSUE THREAD

**Issue by TheMCNerd2017** [GrapheneOS/Vanadium#187]
Sorry if this isn't a valid issue/bug, but this it is something odd I noticed after the latest version of Vanadium got installed through a GrapheneOS update on my device. Basically I was signed out of every site that I was signed in to (luckily I was only signed in to a few so not a big deal to sign back in), despite never clearing the browser cache and site data. This hasn't happened when previous newer versions of Vanadium were installed through system updates, so I'm not sure what caused this behavior to happen with this specific version.

Device: Pixel 4 XL
OS Build: SP2A.220505.002.2022052500
Vanadium version: 102.0.5005.59

**Comment by Zanthed** [comment]
Nothing we can do about it. It might have been some weird one-time thing inherited from upstream. There's nothing for us to fix.
