### ISSUE TITLE
JavaScript JIT isn't capitalized correctly in the page info panel

### ISSUE THREAD

**Issue by sigmafn** [GrapheneOS/Vanadium#193]
As can be seen in the attached screenshot the term "JavaScript" in "JavaScript JIT" isn't capitalized correctly in the page info panel. It's capitalized correctly everywhere else in the UI. 

![Screenshot_20220620-111524](https://user-images.githubusercontent.com/107855363/174593376-924b16c6-0513-4bb5-bd5b-4870e9fdc440.png)

**Comment by flawedworld** [comment]
This is correct, this is how upstream is doing it. See: https://source.chromium.org/chromium/chromium/src/+/main:components/site_settings_strings.grdp;l=80
