### ISSUE TITLE
find a bug in the vanadium repo

### ISSUE THREAD

**Issue by holequantum** [GrapheneOS/Vanadium#208]
vanadium repo does not have gpl license that i have seen before maybe it was bug or github issue kindly make it right. thanks.

**Comment by Zanthed** [comment]
Not really sure what you're trying to say here.

**Comment by holequantum** [comment]
in the license part it is showing unknown but i think i remember it was gpl license before so is it a bug.
just open
https://github.com/GrapheneOS/Vanadium
you will see license column is unknown but that was not the case before.

**Comment by holequantum** [comment]
so i said that it could be a bug so investigate and fix. thanks.

**Comment by rusty-snake** [comment]
The license is detected by GitHub. If at all you must report this as a bug to GH. However GH will not add support for custom situations like Vanadium has (GPL-2.0-only with WebView and Apache-2.0 notes).

**Comment by holequantum** [comment]
okey but last time i check this project i saw there was a license. whatever. thanks your your project and waiting for it to be stable in other than graphene os that you are working on.

**Comment by rusty-snake** [comment]
> **Note**: There was license change last month https://github.com/GrapheneOS/Vanadium/commits/12.1/LICENSE.

**Comment by thestinger** [comment]
It's not a bug.
