### ISSUE TITLE
Disable commonly unused features in Captive Portals

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/Vanadium#210]
Apple is going to be doing this, and it would be nice to have it in Vanadium too: https://github.com/WebKit/WebKit/commit/a58ee48967c30841acd2f85314354a98bb8d0136

**Comment by thestinger** [comment]
The OS captive portal handling is generally what's used and this is already the case there. When opening up in the browser, I think we should handle it like any other insecure site. We already show a full page warning about insecure sites.
