### ISSUE TITLE
Color Inversion Vanadium

### ISSUE THREAD

**Issue by acronymy** [GrapheneOS/Vanadium#213]
Color Inversion is not functioning correctly for Vanadium:

Open a web page in Vanadium. (Incognito or regular)
Toggle Color Inversion on.
Return to Vanadium, find it is now displaying Homepage.
Back swipe closes Vanadium.
Forward arrow in Vanadium is grayed out and cannot be selected.

On 4a with latest update.

**Comment by thestinger** [comment]
Upstream Chromium issue, not going to be addressed by us.
