### ISSUE TITLE
hCaptcha crashes

### ISSUE THREAD

**Issue by ljrk0** [GrapheneOS/Vanadium#214]
Hello,

Vanadium unfortunately is unable to use web sites using hCaptcha.  To verify, click on

https://accounts.hcaptcha.com/demo

and try to solve the captcha, as seen in the screen record:

https://user-images.githubusercontent.com/7831843/183425264-26fd0ff5-5558-48fc-a4f1-77bdf1d582ce.mp4

* GrapheneOS 2022080500
* Vanadium 104.0.5112.69
* Pixel 3a
* Using Sandboxed GPlay through Graphene App Store (all in Beta)
* Logcat containing the crash in the Java app + stack trace in the native binary: [logcat-vanadium.txt](https://github.com/GrapheneOS/Vanadium/files/9282077/logcat-vanadium.txt)

**Comment by qua3k** [comment]
It’s crashing because __cta_atexit calls mremap internally, see https://github.com/GrapheneOS/platform_bionic/commit/afa983c8d44400d45c1f0e2b8e90a8be04acf6f7

**Comment by qua3k** [comment]
The libc should be audited for other operations directly remapping memory rather than going through malloc.

**Comment by thestinger** [comment]
I'll revert this change.
