### ISSUE TITLE
"Open external links in incognito" does not affect WebView

### ISSUE THREAD

**Issue by jamesericdavidson** [GrapheneOS/Vanadium#215]
Steps to reproduce:

1. Open a link within an app (which utilises WebView)
2. Go to Vanadium's History menu, observe that the URL appears in the history

Device details:

- Pixel 4a
- GrapheneOS 20220809
- Vanadium 104.0.5112.69

**Comment by thestinger** [comment]
That's not the WebView.

Our feature doesn't change how Chrome Custom Tabs work yet, and whether or not you move it into a tab in the browser from a Chrome Custom Tab doesn't change how it works. The current feature is for opening links in Incognito and this is not a link.

**Comment by jamesericdavidson** [comment]
Thanks for the clarification

**Comment by rusty-snake** [comment]
chrome://flags/#cct-incognito

Seems to work.
