### ISSUE TITLE
All but one tab lost when updating to SQ3A.220705.004.2022081600

### ISSUE THREAD

**Issue by jeremiah-miller** [GrapheneOS/Vanadium#218]
Title is pretty self explanatory, after updating to SQ3A.220705.004.2022081600 the only tab left was the one i had open before updating, all the others are gone. I did have over 100, so the tab count was the smiley face instead of a number, if that helps narrow the issue down

**Comment by thestinger** [comment]
This is expected based on the upstream changes.

**Comment by jeremiah-miller** [comment]
Yep, i found that in the three dot menu when a tab was open i was aqle to find the old tabs in a different window
