### ISSUE TITLE
Feature request: Option for download notifications

### ISSUE THREAD

**Issue by yaomtc** [GrapheneOS/Vanadium#219]
I have not seen any notifications for downloads. I currently have to open up Files and access the Downloads folder, assuming the file downloaded successfully.

**Comment by BHydden** [comment]
Which device and version are you on? I get notifications every time.

**Comment by thestinger** [comment]
You likely disabled the notification channel. Please check.

**Comment by yaomtc** [comment]
Yup, notifications were disabled. Oops. Thanks!
