### ISSUE TITLE
can we have it for other android devices

### ISSUE THREAD

**Issue by holequantum** [GrapheneOS/Vanadium#222]
Can we have this for other android devices is it possible to have it for other devices.

**Comment by thestinger** [comment]
Not planned. Tons of other stuff to do that's far higher priority.

**Comment by holequantum** [comment]
Okey just provide this then do those tons of work.
I want this to my other devices also having it in graphene is not worth it.

**Comment by holequantum** [comment]
If you can reconsider that again.

**Comment by thestinger** [comment]
Our focus is GrapheneOS.

**Comment by rusty-snake** [comment]
@holequantum pay somebody to do this or do it yourself and you have it.

**Comment by holequantum** [comment]
Okey thanks
