### ISSUE TITLE
Option to disable "add to home screen" pop-ups

### ISSUE THREAD

**Issue by yaomtc** [GrapheneOS/Vanadium#224]
I keep getting these prompts lately. I don't see a way to turn them off.

**Comment by Red00488** [comment]
Any update on disabling the add to home prompt? I still haven't found a solution.

**Comment by thestinger** [comment]
Not planned.

**Comment by yaomtc** [comment]
Is this from upstream?

This happens pretty much every time I visit reddit, and it's very annoying. (Not sure why it doesn't happen with other sites I frequently visit, like reddit.) Looks like the issue has been fixed in Bromite, so I'll try switching to that for a while.

https://github.com/bromite/bromite/issues/2340

**Comment by thestinger** [comment]
I strongly recommend against using a browser consistently behind on security updates. It's off-topic for this issue tracker.

**Comment by yaomtc** [comment]
I remember reading Bromite was recommended in the usage guide, which is why I mentioned it. I see now that any mention of Bromite has been removed since June. So now it's Vanadium or nothing, I see.

**Comment by thestinger** [comment]
Brave is a more reasonable choice than Bromite.

**Comment by yaomtc** [comment]
Thanks for the suggestion. I see they have re-implemented that feature their own way,

https://github.com/brave/brave-browser/issues/25118

I'll try it out.
