### ISSUE TITLE
Persistent "Close all incognito tabs" notification

### ISSUE THREAD

**Issue by idk-r-n** [GrapheneOS/Vanadium#229]
The notification from Chromium browsers that allows a user to close all incognito tabs by tapping the notification is often displayed even when there are no incognito tabs open. Pressing and holding on the Vanadium app and tapping the "New incognito tab " button, visiting a site, then closing the browser (which should clear all incognito tabs), demonstrates this issue.

**Comment by idk-r-n** [comment]
@akc3n It's not a big deal to me, but I see this affect other Chromium browers as well.

**Comment by thestinger** [comment]
Upstream issue.
