### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by io12** [GrapheneOS/Vanadium#239]
Is a night mode for applying a dark theme to websites (instead of just the browser UI) in scope for Vanadium? Would a PR that added this be merged? Kiwi browser, another mobile chromium fork, has this, so it might be possible to port the feature from that.

**Comment by thestinger** [comment]
It has dark mode support for web content already. It respects the system theme by default. This depends on websites implementing support for dark mode, which for example grapheneos.org and GitHub both support. We don't plan on having a **forced** dark mode attempting to alter the CSS used by websites.
