### ISSUE TITLE
Too fast recorded and replayed clips in Common Voice website (Vanadium)(6pro)

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/Vanadium#243]
During a record session i received an OTA update for my Pixel 6 pro. After installing and rebooting the phone the recorded read sentences are at double (or faster) speed with Vanadiun browser on moz Common Voice website.

Examples of screenrecordings with captured sound can be found here:
https://github.com/common-voice/common-voice/issues/3855

Google Pixel 6 pro
TP1A.221105.002.2022111000 beta channel
Vanadium
107.0.5304.105

4 OTA updates before this effect started in Vanadium and still exist.

**Comment by robovoice1** [comment]
Also reported in bugs.chromium.org -=> Status Untriaged(open), pri 3 😀

**Comment by robovoice1** [comment]
https://discuss.grapheneos.org/d/1763-recorded-soundclips-at-double-speed-in-common-voice-website-6-provanadium

**Comment by thestinger** [comment]
Since it appears to be an upstream issue it's going to need to be resolved there.

**Comment by robovoice1** [comment]
The core funtion (contributing voice clips) is functioning again for me since the latest GOS beta channel OTA update TQ1A.221205.011.2022121400! Just donated 200 clips with Vandium browser (108.0.5359.128) without reloading Cv or any tempo effects 😁
