### ISSUE TITLE
Vanadium no longer works with Bitwarden Autofill

### ISSUE THREAD

**Issue by githupper** [GrapheneOS/Vanadium#244]
For at least past 2 release, Autofill option did not pop up for Bitwarden when used with Vanadium. 

Mull is able to work correctly with Bitwarden Autofill function still.

**Comment by thestinger** [comment]
This is a Bitwarden issue:

https://github.com/bitwarden/mobile/pull/2199

Vanadium app id changed to app.vanadium.browser and Bitwarden requires adding every browser to lists.

**Comment by Enlinks** [comment]
@thestinger I wanted to report testing on a formated device this unfortunately still isn't working. Works just fine on my other browser (Fennec).

Also I've tested this on my normal phone running Vanadium in compatibility mode [commit](https://github.com/GrapheneOS/Vanadium/commit/fd37911a5e927298cefbb77e7460ef76219e7280) with the same issue.

```
version 109.0.5414.86

app.vanadium.browser
versionCode 541408633

targetSdk 33
minSdk 29

Installed: Jan 1, 2009; 12:00 AM
```
```
version 2023.1.0

com.x8bit.bitwarden
versionCode 5786

targetSdk 33
minSdk 21

Installed: Jan 22, 2023; 8:53 PM

**Comment by thestinger** [comment]
Bitwarden needs to add support for the new app id. That's not a Vanadium issue. You need to take it up with them if they still haven't shipped that change.

**Comment by Enlinks** [comment]
@thestinger sorry I edited my comment, I included their issue. PR was already done.

**Comment by thestinger** [comment]
You need to be on https://github.com/bitwarden/mobile/releases/tag/v2023.1.0.

**Comment by Enlinks** [comment]
@thestinger I am, its listed in my output above

**Comment by muhomorr** [comment]
@Enlinks Did you install Bitwarden from F-Droid? Is this your thread? https://discuss.grapheneos.org/d/3032-cannot-enable-notifications-on-bitwarden-on-pixel-4a

**Comment by Enlinks** [comment]
@muhomorr yes I'm using the F-Droid version but I'm not using push notifications (that isn't my thread), this is the autofill function. It works just fine with every other app on my phone, it's only Vanadium that's having the problem.

**Comment by Enlinks** [comment]
To add since I forgot to share this, the phone using the compatibility mode version info, Bitwarden version is identical to my test phone:
```
version 109.0.5414.86
org.chromium.chrome
versionCode 541408633
targetSdk 33
minSdk 29
Installed: Dec 31, 2008; 7:00 PM

**Comment by muhomorr** [comment]
@Enlinks Did you enable the Bitwarden accessibility service in Settings -> Accessibility?

It's required for Chromium-based browsers AFAIK.

**Comment by Enlinks** [comment]
@muhomorr thank you for that info, that I wasn't aware of. I enabled that on both phones, however nothing seems to have changed. I even attempted a restart just as a precautionary.

![Screenshot_20230123-115616](https://user-images.githubusercontent.com/110271106/214034031-04b4143e-62ea-43b9-992a-b7ed46e7b49a.png)

**Comment by muhomorr** [comment]
Try following this instruction from GrapheneOS Testing room:

https://matrix.to/#/!AUltSswJuGkDFXqGti:grapheneos.org/$SGtho6Zk9gv6LGPd981enOVSzTyEyzqVMzRk11rDoDE?via=grapheneos.org&via=matrix.org&via=tchncs.de

Quote:
> I have bitwarden autofill working but it was a real pain. In the bitwarden settings for auto-fill services, I needed to enable all 4 options. Vanadium can't handle inliine autofill but draw-over works. The problem occurs when toggling Use accessibility and Bitwarden is grayed out. Tap it to see that it's restricted. You have to give BW permission by going into Settings>Apps>Bitwarden (not within the app but regular settings). Hopefully there will be three dots upper right hand corner. Select and allow restricted. Now, go back to the bitwarden app and select Use Accessibility again. Tihs time it should not be grayed out. Tap it to enable it. Then, finally, go back to the Bitwarden settings to enable draw over. Follow prompts to allow.

**Comment by Enlinks** [comment]
@muhomorr that did the trick, to confirm though, this is not expected to work for those using the compatibility enabled Vanadium?

org.chromium.chrome

If so is there a method to reinstall Vanadium to disable this mode? Id much rather lose the very little data I have on here vs having to factory reset my phone.

**Comment by muhomorr** [comment]
Yes, this will not work for `org.chromium.chrome`. There's currently no way to switch to `app.vanadium.browser` without reinstalling the OS.

**Comment by thestinger** [comment]
Note: factory reset counts as a fresh install and will use app.vanadium.browser.

**Comment by thestinger** [comment]
It should work fine for `org.chromium.chrome` because they already supported it previously. It was when we switched to `app.vanadium.browser` that it stopped working and needed the new app id added. Note that a factory reset counts as a fresh install and will use `app.vanadium.browser`.

**Comment by Enlinks** [comment]
Sorry @muhomorr for the late response. I appreciate everyones help and hard work you all do!
