### ISSUE TITLE
[Question] What would be the most similar browser for PC?

### ISSUE THREAD

**Issue by igonro** [GrapheneOS/Vanadium#248]
In terms of privacy Brave and Firefox are the most recommended browsers. As far as I know chromium based browsers are generally safer.

What would be the most similar browser to Vanadium for PC (Windows / Linux)? Brave? Chromium? Ungoogled Chromium? Other?

I want it to be privacy friendly, but also secure.

Feel free to close this issue and label it with Question.

Thanks!

**Comment by thestinger** [comment]
We can't answer questions or provide support on our issue trackers. We also don't provide official recommendations like this.
