### ISSUE TITLE
enable local storage backup and restore, encrypted

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/Vanadium#251]
Local backups of settings, JS settings, Bookmarks, Entries, Passwords, in a usual format would make sense.
- keepass Format (Username, password, URL)
- something else

## Alternative Solution:
Use Googles protocols for Cloud backup and replace Googles server for Account sync. etc with an own one, but I dont think this makes sense.

**Comment by thestinger** [comment]
Duplicate of https://github.com/GrapheneOS/Vanadium/issues/102.

**Comment by zuble** [comment]
This would be really helpfull, as there isnt any way of sync tabs with another machines, by allowing to export bookmarks (.html) localy , its possible to use floccus to import those same tabs and therefore achieve somehow tabs sync.
