### ISSUE TITLE
Enable LibRedirect

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/Vanadium#253]
wRedirect links from common media monopoles like Google, Youtube, Google Maps, Reddit, Quora, ... to open source community driven frontends.

This feature uses a local database of running instances and randomly chooses them. It could be opt-in.

[Here is the source-code for the Firefox Addon](https://cloud.uol.de/s/ZABmjEGCLz5iJNi)

[And here is the Github repo](https://github.com/libredirect/libredirect)

**Comment by thestinger** [comment]
This isn't planned.
