### ISSUE TITLE
[Vanadium changes] Enable custom search engines

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/Vanadium#254]

**Comment by thestinger** [comment]
OpenSearch metadata is already used to support adding custom search engines.

**Comment by thestinger** [comment]
Chromium already supports OpenSearch metadata on Android for adding search engine not included in the baseline choices. We don't plan on maintaining patches to expose the extra customization available in desktop Chromium. It would be too much to maintain and too niche for the scope of our work.
