### ISSUE TITLE
Enable NoScript

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/Vanadium#255]
Vanadium offers some form of JS blocking, similar to the Firefox Addon "noJS". This disables all Javascript for domains but the list can neither be exported or imported, so it takes an eternity to set up.

## Better solution
whole Implementation of the addon. I guess this is not possible using Chromium Android as base.

NoScript allows detailed blocking of Javascript types: script, object, media, frame, font, webgl, fetch, ping, noscript, unchecked CSS, LAN, other

## Alternative solution
Set a preset of blocked Javascript domains. 

Problem:
- No differenciation of Javascript types like with NoScript, 
- no JS just breaks most sites and its unsure of third party javascript from a site is blocked on another one
- No easy on-off switch for user-friendlyness, for example Google reCaptcha (requiring gstatic, recaptcha.com, google.com)

**Comment by thestinger** [comment]
This isn't within the scope of Vanadium. It's not the way we want to approach these things and is not a actually a good approach for privacy and security, especially for it to be user friendly.
