### ISSUE TITLE
Return random used storage when websites request it

### ISSUE THREAD

**Issue by loyl1** [GrapheneOS/Vanadium#257]
Websites requesting device used/free storage to fingerprint users can be mitigated by returning a random amount. This would enhance privacy in Vanadium. Could be set to per tab or per session.

**Comment by thestinger** [comment]
This won't work without actually making the storage unavailable or they can test to see how much is available. Incognito mode restricts this by setting a smaller fixed amount of storage as usable. We could make that available outside Incognito but that's a different feature than this request.
