### ISSUE TITLE
Safebrowsing is off - but giving a popup

### ISSUE THREAD

**Issue by fuzzblob** [GrapheneOS/Vanadium#259]
My safe browsing setting is off, but I just got a warning visiting [https://www.perfectly-nintendo.com/descenders-switch-software-updates/](https://www.perfectly-nintendo.com/descenders-switch-software-updates/) which had a "learn mpre" link leading to [https://support.google.com/chrome/answer/99020?visit_id=638071820658232121-2436357088&p=safety_tip&rd=1#safety_tip](https://support.google.com/chrome/answer/99020?visit_id=638071820658232121-2436357088&p=safety_tip&rd=1#safety_tip).

![Screenshot_20221220-171451_1](https://user-images.githubusercontent.com/13321200/208802538-5c5df9c4-49cc-4b5c-b442-478a57a85e29.png)

[Edit: I never had it enabled to begin with]

**Comment by r3g-5z** [comment]
This isn't Google Safe Browsing. This is a standard Chromium feature just alerting for potential typosquatting/DGAs/lookalike-domains.
https://chromium.googlesource.com/chromium/src/+/HEAD/docs/security/lookalikes/lookalike-domains.md

In this case, it's a simple false positive that you can ignore.

The URL you posted is not classified by Google Safe Browsing as malicious.

https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fwww.perfectly-nintendo.com%2Fdescenders-switch-software-updates%2F&hl=en
https://urlscan.io/result/68f672f8-5f01-46b7-af9a-02571041e9da/
