### ISSUE TITLE
Vanadium Crashes on File Upload

### ISSUE THREAD

**Issue by nimdajitam** [GrapheneOS/Vanadium#266]
Vanadium crashes (gets terminated) whenever and wherever I try to upload files (for ex.: adding attacment via webmail client, trying to upload picture on random websites). I've checked permissions and all seems ok.  Bug is reproducible.

Vanadium v. 110.0.5481.61

GOS v. TQ1A.230105.002.2023020200

If you need any logs, more data (versions of other frameworks and components), I'll do my best.

**Comment by thestinger** [comment]
This is resolved by the next release of the OS already.
