### ISSUE TITLE
implement native Android autofill to replace Google Play autofill

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Vanadium#276]

**Comment by raptor170** [comment]
Will this change affect the way autofill works for such apps like bitwarden etc.?

**Comment by ljrk0** [comment]
Yes, it will work better as BitWarden won't require any draw over or similar permissions for Vanadium anymore.

**Comment by yaomtc** [comment]
So once this is implemented, KeePassDX should work without having to switch back and forth between keyboards?

**Comment by ljrk0** [comment]
Likely, but all this is better discussed in the graphene forum.
