### ISSUE TITLE
Credential autofill service pasting username into address bar

### ISSUE THREAD

**Issue by JoonasC** [GrapheneOS/Vanadium#288]
Autofilling credentials has recently started working in Vanadium, but for some reason the username gets pasted into the address bar. I am using the KeepassDX password manager.

**Comment by JoonasC** [comment]
This is happening on all sites.

**Comment by thestinger** [comment]
The app's autofill implementation is not handling things well when sites are weird and is falling back to URL bar.

**Comment by thestinger** [comment]
The URL bar is specially marked as not being interesting to autofill but autofill apps can see it and fill it out since autofill isn't only for passwords.

**Comment by JoonasC** [comment]
I just tried a site I haven't tried yet (GitHub) and it works properly, so it does indeed seem like it is site specific.

**Comment by thestinger** [comment]
That doesn't make it a site issue. It's a wrong assumption. As is this looks like a bug with how this app is doing autofill. We could perhaps change something to make it easier for the app but they could also solve it.
