### ISSUE TITLE
Cannot export open tabs, bookmarks

### ISSUE THREAD

**Issue by cmonty14** [GrapheneOS/Vanadium#298]
Hi,

I want to export open tabs, however this function is not available.

Other browsers, e.g. Bromit, include a feature to store all open tabs as bookmarks.
This function is not avaiable, either.

And in addition I cannot export bookmarks.

Please advise how to export open tabs and bookmarks in Vanadium.

THX

**Comment by rusty-snake** [comment]
#168

**Comment by r3g-5z** [comment]
Duplicates of https://github.com/GrapheneOS/Vanadium/issues/102 and https://github.com/GrapheneOS/Vanadium/issues/149
