### ISSUE TITLE
Notifications remain after completing download

### ISSUE THREAD

**Issue by ProgrammerWhoPrograms** [GrapheneOS/Vanadium#300]
Download notifications stay as though the files are still downloading, but they show "$filesize / $filesize completed".
This clutters up the notifications menu and annoys me with downloading animations in the top bar.

**Comment by thestinger** [comment]
We don't plan to change this standard Chromium behavior.

**Comment by ProgrammerWhoPrograms** [comment]
It also does this partway through the download. Is that standard Chromium behaviour?

**Comment by thestinger** [comment]
It is standard Chromium behavior. We don't change this.

**Comment by ProgrammerWhoPrograms** [comment]
Someone also suggested that the downloads that appeared 100% were actually slightly less but too slight to register.

**Comment by thestinger** [comment]
There are no changes to this by Vanadium. It sounds like you have a network issue.

**Comment by ProgrammerWhoPrograms** [comment]
It's definitely not a Chrome or network issue as it works on Chrome. It also works on both Chrome and Vanadium (and Firefox) in a new profile I created for testing.
The downloads don't appear to be corrupted however, so it is only a cosmetic issue (but still an issue).
I will turn off download notifications.

**Comment by xn-7492** [comment]
I had this issue too, it is caused by disabling the 'Completed downloads' notification category, while 'Active downloads' is enabled.
This seems to be default behaviour for chromium based browsers on Android.

**Comment by Yolakalemowa** [comment]
> I had this issue too, it is caused by disabling the 'Completed downloads' notification category, while 'Active downloads' is enabled. This seems to be default behaviour for chromium based browsers on Android.

hi sorry where can I find this toggle? the banner is so annoying.

**Comment by xn-7492** [comment]
> > I had this issue too, it is caused by disabling the 'Completed downloads' notification category, while 'Active downloads' is enabled. This seems to be default behaviour for chromium based browsers on Android.
> 
> hi sorry where can I find this toggle? the banner is so annoying.

You can access the notification settings for Vanadium either from "App info" or from a shortcut in the Vanadium settings. From there you can toggle "Active downloads" in the "General" notification category on.
If you never changed the notification settings, your issue might be caused by some other upstream bug.

**Comment by Yolakalemowa** [comment]
@xn-7492 oh I just checked and I have all notifications turned off... must be upstream like you said.
