### ISSUE TITLE
[Feature Request] Choose search engine in omnibar

### ISSUE THREAD

**Issue by kekkoudesu** [GrapheneOS/Vanadium#309]
Firefox has a feature which allows you to search with any search engine on your list. It displays the favicons for the search engine at the bottom when you are typing in the omnibar. I often use it when I want to search Wikipedia; rather than going through a search engine like Mojeek, I use Wikipedia's search engine directly. 

This feature allows you to access all of your search engines for every search, even if you have a default preference. I oftentimes want to use Mojeek, but there are queries I know Brave Search handles better.

**Comment by thestinger** [comment]
We don't plan to change this. Ask for them to add this desktop Chromium feature to Android.

**Comment by thestinger** [comment]
It is a Chromium desktop feature.
![2023-04-24-103245_826x183_scrot](https://user-images.githubusercontent.com/1505226/234028529-f4855d5a-9f50-429c-80b5-685e15ed69d7.png)

**Comment by kekkoudesu** [comment]
This is similar to what I'm asking for, though different. Firefox implements both of these things on the Desktop version (shortcuts + list of icons to click). But keyboard shortcuts would be good enough.
