### ISSUE TITLE
How to add an URL to Vanadium's homepage

### ISSUE THREAD

**Issue by AchMenz** [GrapheneOS/Vanadium#315]
Dear developers,

I can find no possibility to modify Vanadium's homepage (The page that is opened if you click on the top left home button.).

I would like to know how to add a web page to this homepage manually and permanently. I only recognize that some pages land there somehow automatically, more like a small portion of the browser history. But I would like to see a distinct set of bookmarks there that I have defined.

**Comment by thestinger** [comment]
It doesn't really support this. We can change how it works later but for now we're not going to deviate much from the Chromium approach to this.
