### ISSUE TITLE
build script doesn't work

### ISSUE THREAD

**Issue by LeOS-GSI** [GrapheneOS/Vanadium#316]
I have used the tutorial from here https://grapheneos.org/build#browser-and-webview, step by step. All patches are applied. 
But 'm getting theses errors and build doesn't start

```
`Vanadium/src$ chrt -b 0 ninja -C out/Default/ trichrome_webview_64_32_apk trichrome_chrome_64_32_apk trichrome_library_64_32_apk
ninja: Entering directory `out/Default/
[0/1] Regenerating ninja files
ERROR at //chrome/android/BUILD.gn:2553:3: Unknown function.
  monochrome_public_apk_or_module_tmpl("trichrome_chrome_apk") {
  ^-----------------------------------
See //BUILD.gn:404:11: which caused the file to be included.
          "//chrome/android:chrome_public_apk",
          ^-----------------------------------
FAILED: build.ninja 
../../../../../../../usr/bin/gn --root=../.. -q --regeneration gen .
ninja: error: rebuilding 'build.ninja': subcommand failed
```
`

**Comment by thestinger** [comment]
You don't appear to have fully checked out the sources.

**Comment by LeOS-GSI** [comment]
haven't you read what I have written ?? The build does NOT start. So what should I find in out directory ???????????????????????

**Comment by thestinger** [comment]
You may have missed an error message in an earlier step. It does not appear things are properly synced, etc.

**Comment by LeOS-GSI** [comment]
And this error message is located in out folder ??

In the meantime I have run the whole HowTo 2 times. No error message while doing. I have checked several patches which are related to the error message. I have check the 'args" serveral times. all as written. But still getting the error message

**Comment by thestinger** [comment]
Trichrome is not ours.

**Comment by LeOS-GSI** [comment]
> Trichrome is not ours.

I can't believe . isn't that YOUR build command ?

`chrt -b 0 ninja -C out/Default/ trichrome_webview_64_32_apk trichrome_chrome_64_32_apk trichrome_library_64_32_apk`

There is 3 times written 'trichrome' !!!

**Comment by thestinger** [comment]
Trichrome is the standard modern Chrome / Chromium build for browser + WebView with a shared library. We only add an APK build target for the browser instead of using their bundle target and then generating a universal APK from it partly because it is leaner to just build the APK directly. We know our Chromium build instructions work fine with the current release and development branch. It is likely there is an earlier error message before the one you are showing, such as when syncing or when applying the patches.

**Comment by LeOS-GSI** [comment]
OK I have made a complete new start, from beginning on.
I have applied all patches, one by one, to ensure all are applied. Including **YOUR** 0070-add-trichrome-browser-apk-targets.patch.  All applied successful.
then I have made successful the gclient sync
and then I have done the `gn args out/Default` which was ending with this error:
```
Generating files...
ERROR at //chrome/android/BUILD.gn:2546:3: Unknown function.
  monochrome_public_apk_or_module_tmpl("trichrome_chrome_apk") {
  ^-----------------------------------
See //BUILD.gn:403:11: which caused the file to be included.
          "//chrome/android:chrome_junit_tests",
          ^------------------------------------
```
I have double checked the  0070-add-trichrome-browser-apk-targets.patch. all applied.

So what is the issue ?

**Comment by thestinger** [comment]
`template("monochrome_public_apk_or_module_tmpl")` is defined there. You're doing something wrong.
