### ISSUE TITLE
Add vanadium to fdroid.

### ISSUE THREAD

**Issue by not-programmer98** [GrapheneOS/Vanadium#318]
Could you add vanadium to fdroid? It would be a more convenient way to install and update app for non-grapheneOS users

**Comment by r3g-5z** [comment]
We're not interested in submitting any of our apps to F-Droid and request no one submits our apps there.

**Comment by r3g-5z** [comment]
Vanadium also is not suitable for non-GrapheneOS use at this time.

**Comment by thestinger** [comment]
Our apps are distributed with our app repository, not F-Droid.

**Comment by not-programmer98** [comment]
Where's your app repo
