### ISSUE TITLE
Warn for obsolete cipher suite

### ISSUE THREAD

**Issue by idk-r-n** [GrapheneOS/Vanadium#319]
Chromium only notes that a website is using an obsolete cipher suite when security after tapping the padlock in the address bar. Vanadium should not load the page without explicit user approval, similar to an insecure HTTP warning.

**Comment by r3g-5z** [comment]
Essentially a duplicate of https://github.com/GrapheneOS/Vanadium/issues/228

**Comment by idk-r-n** [comment]
How is this a duplicate? Nothing is supposed to be configured. The warning already exists in Chromium, I'm just suggesting that it be shown before the page is loaded.
