### ISSUE TITLE
self-signed certificates in vanadium don't work?

### ISSUE THREAD

**Issue by kubuntu-newbie** [GrapheneOS/Vanadium#320]
This could be just me not understanding how to configure it right. I posted this question on grapheneos forum but got no answers:

I'm trying to access a web server (Nextcloud) that uses self-signed certificate on a local network using Vanadium. I have installed this certificate in the Settings - Security - More Security Settings - Encryption & credentials - Install a certificate - CA certificate and it shows up under Trusted credentials / User.
When I try to access the server using https through Vanadium I get an error NET:ERR_CERT_AUTHORITY_INVALID.
I have no problems using the same self-signed certificate in iOS on iPhone or on any of the computers (Windows, Linux) on my local network.
What am I doing wrong? How do I get it to work?

Thank you.

**Comment by thestinger** [comment]
There's something wrong with your certificate and the same thing would happen in Chrome on the stock Pixel OS.

**Comment by kubuntu-newbie** [comment]
> 

I very much doubt that the problem is with the certificate itself - as I mentioned before it works in Windows 10, it works in Linux (Ubuntu 23.04) and it works in iOS - I'm able to connect browsers, Nextcloud client and Joplin to my Nextcloud server without any problems using this same certifcate.
The certificate was created on a linux box using

openssl genrsa -passout file:passfile -des3 -out my.key 2048
and
openssl req -passin file:passfile -x509 -new -nodes -key my.key -sha256 -days 825 -out my_ca.crt

the certificate hasn't expired yet

Is there something specific to Chrome/Pixel OS that requires creating a certificate in a different way from what works in Windows/Linux/iOS?

**Comment by kubuntu-newbie** [comment]
> 

When I click on the left "red warning" sign in the address, I get:

The identity of this website isn't verified
   Server's certificate is not trusted

Certificate information is correct. Below the button "Turn on warnings" it says:
Your connection to server_name is encrypted using a modern cipher suite
The connection uses TLS 1.3
The connection is encrypted and authenticated using AES_128_GCM and uses X25519 as key exchange mechanism.

So why does Vanadium says certificate is not trusted if I have it added as described in the original question. Is there something else I need to do to explicitly state that I trust the certificate?

**Comment by kubuntu-newbie** [comment]
Also, if I uninstall the certificate I installed earlier, Vanadium behaves in exactly the same way and gives me exactly the same details.

**Comment by kubuntu-newbie** [comment]
I might have figured out what I did wrong, I used basicConstraints=CA:FALSE when creating my certificate and according to the https://stackoverflow.com/questions/37281958/how-to-trust-self-signed-certificate-on-android, it is supposed to be CA:TRUE.
I haven't tested this yet, and unlike in the above link GrapheneOS didn't have any problem importing my certificate with basicConstraints=CA:FALSE.

**Comment by thestinger** [comment]
Expiry shouldn't be more than 1 year ahead, etc. It still needs a valid CN.

**Comment by kubuntu-newbie** [comment]
thank you!
got it sorted out

**Comment by kanthans** [comment]
> 1 year expiry or less or required. You should have automatic renewal so the expiry shouldn't be long. It's likely going to drop to 90 days at some point.

Thank you for your quick response.
