### ISSUE TITLE
Separated/Tagged Bookmarks

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/Vanadium#335]
When Bookmarks are saved, they appear to be saved & stored globally with no indication of whether they were intended/saved to be later reopened in incognito or a standard tab.

For an example, while in incognito mode, bookmarking  "scholar.google.com" is saved and is placed into the centralized bookmarks folder.

It is presumed that as this bookmark was saved while in incognito, it is intended to be opened and used again, while in incognito.

However, this does not appear to be the case.  When opening a Bookmark, which was saved while in incognito, the bookmark opens the link in a standard, non-incognito.

A user must create an extra step and manually select to open an incognito tab, then they must select a saved bookmark to open in incognito.

I suggest a compartmentalized, separated, or tagged bookmarks, to differentiate between bookmarks saved in incognito or standard... and for them to open in their designated standard/incognito tab,  as they were originally saved and intended to be reopened in without having to actively select an incognito tab to be open prior to selecting a bookmark.

**Comment by thestinger** [comment]
We don't plan to change this kind of thing downstream. Recommend not making bookmarks in Incognito.
