### ISSUE TITLE
Detected as Linux

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/Vanadium#350]
I dont get Chromium, I prefer Firefox.

But a big argument for it is fingerprintability, as Chrome on Android poorly is really common.

Now I got a mail from vinted.fr that a device "Chrome on Linux" logged in. So GrapheneOS Vanadium doesnt have the Chrome Android fingerprint, which makes it veeery fingerprintable.

Also many sites display as Desktop mode always, this doesnt happen on Firefox mobile.

Latest versions, Pixel 4a

**Comment by thestinger** [comment]
Incorrect information.
