### ISSUE TITLE
Problems with Vanadium System Webview 

### ISSUE THREAD

**Issue by Beerman0815** [GrapheneOS/Vanadium#359]
I have some problems with the new Vanadium System Webview version (116.0.5845.114.1).

Some apps do not want to load content. Like "Amazon Shopping" or the "Post & DHL" app. The apps load all the time but no content comes.

![DHL_POST](https://github.com/GrapheneOS/Vanadium/assets/143692033/60cc14e1-3d72-4221-a7f6-10be00bd7688)
![Amazon_Shopping](https://github.com/GrapheneOS/Vanadium/assets/143692033/9bfad043-2759-4fae-86cf-8525ce8732b5)

If I uninstall the updates under the app setting of "Vanadium System Webview" and go back to 115.0.5790.166.0, these apps work again and the content of these apps loads fast.

![Amazon_Shopping_Woriking_with_ver_115](https://github.com/GrapheneOS/Vanadium/assets/143692033/9f283302-9a32-468a-a5a7-ccb763edd669)

Unfortunately, the latest updates from the alpha channel do not work for me either.

**Comment by Me0wzz** [comment]
Same issue here. Apps that use webview does not load contents properly.

Webview version: 116.0.5845.163.0

**Comment by akp37** [comment]
Same thing is happening on my pixel 6

**Comment by thestinger** [comment]
Will be addressed by rolling back the feature added in 116.0.5845.114.1.

**Comment by Beerman0815** [comment]
116.0.4835.114.0 works for me, yes.

Thx!

**Comment by flaep** [comment]
can confirm, webview 116.0..5845114.0 works with DHL and amazon

**Comment by thestinger** [comment]
Vanadium 116.0.5845.163.1 is available in the app repository. Please update to that and let us know if it resolves the issue. We need reports back about this as quickly as possible to begin working on a fix for the new feature instead of removing it.

**Comment by Beerman0815** [comment]
Updated to 16.0.5845.163.1 and it is working for me. 🙂

**Comment by akp37** [comment]
Updated, and it is also working on pixel 6. Thank you, Daniel, and beerman for creating a ticket

**Comment by flaep** [comment]
Can confirm aswell, that amazon and dhl work on pixel6 with  16.0.5845.163.1

**Comment by pjsxw** [comment]
I'm still seeing this issue (or another with the same symptoms) with 116.0.5845.172.0

Is there documentation for how to revert to a previous version to see if that resolves it? @Beerman0815 mentioned doing so earlier in the thread, but I can't see an option to uninstall the update in either Apps or the system settings

**Comment by flaep** [comment]
the uninstall updates button is missing for ne aswell. New issue?

![IMG_20230908_211639](https://github.com/GrapheneOS/Vanadium/assets/10746154/f2f5b753-7e5d-4d0d-9aba-5f134c85c014)

**Comment by rusty-snake** [comment]
If you updated your OS to a version that includes the latest version, this is expected.
