### ISSUE TITLE
remove or replace learn more link on blank incognito tab

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Vanadium#36]

**Comment by refragable** [comment]
It appears that the "Learn more" link in the blank incognito tab has been directing users to https://grapheneos.org/usage#web-browsing 
ever since [PR #39](https://github.com/GrapheneOS/Vanadium/pull/39) was merged.

Tested on Pixel 4 running the latest prebuilt Vanadium (84.0.4147.111).

**Comment by thestinger** [comment]
Yes there's now a fallback directing people to our site.

**Comment by thestinger** [comment]
That's because the fallback URL has been configured to direct people to our documentation. All of these links to specific documentation still need to be either removed or replaced.

**Comment by thestinger** [comment]
There is no URL configured for this or the others, so they use the fallback support URL which was changed in #39. It doesn't mean this issue is resolved. It only resolved generic cases where specific documentation is not really expected.

**Comment by refragable** [comment]
Is there a specific link you would like to see configured for this instance of "Learn more"?

**Comment by thestinger** [comment]
No, since the documentation would need to be written about it in order to link to it. Alternatively, it can just be removed for the time being. Doesn't make sense to have a link to generic, irrelevant documentation via the fallback.
