### ISSUE TITLE
Spoof app theme for websites

### ISSUE THREAD

**Issue by topminipie** [GrapheneOS/Vanadium#370]
Add option for spoof app theme for websites (give the site a light theme, even if the browser is set to a dark theme).
This will make the browser/user more like the average browser. (Browser fingerprint)

**Comment by rusty-snake** [comment]
Settings > Design > System|Light|Dark

---

TBH this is one bit entropy. If you want to mitigate fingerprinting start with e.g. Canvas that provide much more bits of entropy.

**Comment by thestinger** [comment]
If you want to force light theme, use the light theme within the browser. There's little usability difference.
