### ISSUE TITLE
Unusuable "flashing" interface on clean launch

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [GrapheneOS/Vanadium#382]
https://github.com/GrapheneOS/Vanadium/assets/13170204/b5116797-15ed-4298-bf2c-612cb1e9514f

It happen on 
```
version 118.0.5993.65.0

org.chromium.chrome
versionCode 599306532

targetSdk 34
minSdk 29
```
On a Pixel 4 (flame) TP1A.221005.002.B2.2023100300
Latest stable Android 13 build.

Uninstalling updates to go back to
```
version 117.0.5938.140.0

org.chromium.chrome
versionCode 593814032

targetSdk 34
minSdk 29
```
Make it work again as it should.

This is a specific issue with Vanadium itself, but not it's WebView component, as using an another Webview browser (As the DuckDuckGo browser) doesn't cause any issues.
You also did noticed that i was able to open the browser fine for the first time. This seems to happen if you open the browser via an external app _as to open a link_. Then, even after clearing out the opened tabs, it behave fine.

**Comment by thestinger** [comment]
Force stop the app, run `adb logcat -c` to clear logs and then open the app and run `adb logcat -d > log.txt` to get logs.

**Comment by PoorPocketsMcNewHold** [comment]
Seems to have fixed itself on alpha
```
version 118.0.5993.80.0

org.chromium.chrome
versionCode 599308032

targetSdk 34
minSdk 29

Installed: 1 janv. 2009; 01:00
Updated: 17 oct. 2023; 06:40
```
Will re-open and show those adb logs (Haven't had access to a properly working computer with android tools) if it happen again.
