### ISSUE TITLE
Youtube Music Background Playback doesn't work

### ISSUE THREAD

**Issue by maof97** [GrapheneOS/Vanadium#393]
Trying to play YouTube Music in the background doesn't work. If you are putting the app in the background or lock the screen the sound pauses after half a second. The controls to control the song is present in the notification bar for about 1 second longer and then just disappears, making it impossible to continue playing the music. I have YT Premium so the feature should not be blocked from YouTube's side.

I tested it on Firefox for Android where it works (but playback controls are missing, which is why I tried using Vanadium)

I tested Youtube and Spotify in Vanadium which also work without a problem. It seems to only affect music.youtube.com.
I am using the latest GrOS and Vanadium (stable).

Can anybody reproduce this?

**Comment by thestinger** [comment]
YouTube doesn't support this in their mobile site, only the app. The mobile site avoids using the media session API able to play in the background to force you to use the app. Firefox doesn't implement it in the same way so sites can play audio in the background without a session.
