### ISSUE TITLE
Zepp / Satispay maps don’t work

### ISSUE THREAD

**Issue by xunil89** [GrapheneOS/Vanadium#396]
I am not entirely convinced but I think that this is due to vanadium, in the app Zepp has never worked the section (training details) now has added the lack of the map in the training register after the latest updates, I also realized that the satispay app no longer works in the local find section on the map. i have android 13 crdroid with microg. does anyone manage to play my bugs?

**Comment by thestinger** [comment]
GrapheneOS with the sandboxed Google Play compatibility layer offers much better app compatibility than microG. That's your issue.
