### ISSUE TITLE
add support for Chromium downloads via ACTION_CREATE_DOCUMENT

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Vanadium#4]

**Comment by thestinger** [comment]
Going to need to wait and see what happens with Android Q.

**Comment by thestinger** [comment]
Downloads are now restricted to download directories, so that's probably how they intend to support Android Q. Whether or not this still makes sense depends on whether those are accessible to other apps with Scoped Storage enabled for them. This feature won't be needed to avoid the Storage permission(s) anymore though.

**Comment by csagan5** [comment]
@thestinger I assume this is the reason behind the changes we discussed in #17

**Comment by thestinger** [comment]
Yeah, I think so, but I think they made a mistake by not having user confirmation even when there's a single download directory. They didn't seem to care when I pointed out the issues with it such as exposing the attack surface of the Android media stack.

**Comment by thestinger** [comment]
I'm fine with how this works on Android 10 with the new download code backported. There are some quirks like the fact that the Storage permission can still be requested by the app even though it targets API 29, perhaps because apps bundled with the base system don't go through the install process for temporarily granting it or not granting it.
