### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by bootlesshacker** [GrapheneOS/Vanadium#412]
Hi

Vanadium seems to be DNS leaking to Google's servers. I cannot replicate this issue on Firefox. I also cannot replicate this issue on other devices at home.

My home network has a DNS server that uses Cloudflare (and only CF) upstream. However, according to ipleak.net, Google's DNS servers are occasionally being hit. This only happens on WiFi - when using my mobile providers 4g, it only shows my mobile providers DNS servers.  This issue is much more reproducible if I start the test on ipleak.net, disconnect WiFi, and reconnect it, and then restart the test. Prior to doing this reconnect, only the occasional hit goes to Google. After doing it and refreshing, almost every hit goes to them until I restart the Vanadium app. Secure DNS is off in the browser settings, and private DNS is off on phone settings. I have only noticed this issue recently.

Vanadium build 119.0.6045.163.1

Any thoughts?

**Comment by bootlesshacker** [comment]
Just for avoidance of doubt, the DNS servers on my WiFi profile is my local one which only uses CF upstream. Also reaffirmed by other browsers not getting the same issue

**Comment by thestinger** [comment]
This appears to be a network issue, not a GrapheneOS issue. Test a different Wi-Fi network.
