### ISSUE TITLE
Remove non-privacy search engine

### ISSUE THREAD

**Issue by Pantyhose-X** [GrapheneOS/Vanadium#414]
It will give you country-specific results based on your country's ip, if you search for some non-popular sites in other countries, you won't find results, you chose other Regions in the search engine and he will still give you specific results based on the ip location.

non-privacy search engine
Yahoo
Bing
DuckDuckGo

privacy search engine
Brave
eu.startpage.com
us.startpage.com
Yandex
qwant.com
Google  #Gives specific results based on IP address, not very serious

**Comment by thestinger** [comment]
We don't plan to remove search engines from the list for no particular reason. We could switch to a new default since DuckDuckGo lacks substance behind the privacy marketing but there isn't really a good option.
