### ISSUE TITLE
Other android devices support

### ISSUE THREAD

**Issue by Clownium42** [GrapheneOS/Vanadium#415]
I would like to build vanadium for other android devices, but have a hard time to find which patch that are specific to malloc.
Is it possible to remove this dependency somehow?

**Comment by rusty-snake** [comment]
Does it fail to build? Or do you ask because of

> **For example**, GrapheneOS already provides a hardened malloc implementation so there's *no need* for Vanadium *to replace* it.

**Comment by Clownium42** [comment]
It does not fail to build. I am just wondering which of the patches that are specific to hardened malloc.
