### ISSUE TITLE
Option to limit the number of open tabs

### ISSUE THREAD

**Issue by drugdeliverthatwantprivacy** [GrapheneOS/Vanadium#423]
It would be great if you could add an option to limit the number of open tabs to only keeping the last 10 or 15 tabs or a certain number because normally I don't pay attention to whether I usually close the tabs and after several hours i have 50 open tabs in the browser, which I don't know if it can affect its security

**Comment by thestinger** [comment]
It does put inactive tabs out of memory. You can organize them into tab groups.
