### ISSUE TITLE
on-device translation feature

### ISSUE THREAD

**Issue by soupslurpr** [GrapheneOS/Vanadium#432]
I think an on-device translation feature would be really cool, maybe using [Candle](https://github.com/huggingface/candle) and these models https://huggingface.co/Helsinki-NLP/opus-mt-en-es (around 300 MB per language to language model, e.g. English to Spanish and Spanish to English are separate models).

Just an idea, if the project doesn't have enough resources or maintaining this might be too time consuming, that makes sense.

**Comment by thestinger** [comment]
We really don't have the resources for it any time soon.
