### ISSUE TITLE
Set favourite search engine to startpage

### ISSUE THREAD

**Issue by paride15** [GrapheneOS/Vanadium#45]
On Bromite I can easily set my favorite search engine on Startpage. Is it possible to do it here too?

**Comment by beerisgood** [comment]
See https://github.com/GrapheneOS/Vanadium/issues/6

**Comment by thestinger** [comment]
You can already add search engines and change the default.

**Comment by git70** [comment]
Excuse me, but how can I add a search engine and change to the default?
In Vanadium 95.0.4638.74 I see only four and I have no option to add:
Google
Yahoo
Bing
DDG

**Comment by thestinger** [comment]
You can add one as long as it has open search metadata. Visit it, use it, then switch to it in settings.

**Comment by git70** [comment]
I did as you wrote, but it does not work :(
Can you check this for startpage.com?

**Comment by git70** [comment]
Metager.org also does not work.
Despite the description that he should work metager.org/plugin

**Comment by julian-urban** [comment]
For anyone still encountering this problem, it's not Vanadium's fault. You need to follow the [instructions](https://support.startpage.com/hc/en-us/articles/8623502498964-Make-Startpage-the-default-search-engine-in-Chrome-Android-) for configuring startpage as the default, specifically switching from POST to GET. It should appear as an option in the Vanadium settings after doing one search with GET.

**Comment by bocekm** [comment]
> For anyone still encountering this problem, it's not Vanadium's fault. You need to follow the [instructions](https://support.startpage.com/hc/en-us/articles/8623502498964-Make-Startpage-the-default-search-engine-in-Chrome-Android-) for configuring startpage as the default, specifically switching from POST to GET. It should appear as an option in the Vanadium settings after doing one search with GET.

Nowadays one more step is needed for StartPage to appear in the list of search engines in Vanadium. Similar to what one needs to do in [Cromite](https://github.com/uazo/cromite/issues/238#issuecomment-1804841358), it's necessary to switch at least temporarily the `Cross-origin referrer policy` in the `Privacy and security` settings of Vanadium to `Disable cross-origin referrer`.

**Comment by bocekm** [comment]
Disabling the referrer and setting Startpage to use GET instead of POST does not work for me anymore, Startpage does not show up for me in the list of search engines.
