### ISSUE TITLE
Enable DNS Over HTTPS

### ISSUE THREAD

**Issue by paride15** [GrapheneOS/Vanadium#46]
This is possible on Bromite but they let you choose only from a few providers. They also recommend the use of Cloudflare, which is ridiculous for a browser that calls itself privacy-oriented. I don't trust Cloudflare and I wish I could choose my provider as I can easily do in Firefox. For example I would like to be able to set CZ.NIC's DoH.

**Comment by csagan5** [comment]
@paride15 all options have been carefully considered in the past, including the [Mozilla/Cloudflare partnership](https://github.com/bromite/bromite/issues/164). You can choose any of the available providers, the suggestion is obviously based on the available options.

I invite you to be more constructive and propose better options if you know any; also, "I don't trust Cloudflare" needs to be fact-based, opinions don't cut it.

**Comment by paride15** [comment]
I absolutely didn't want to seem un-constructive and I apologize if I seemed so. I was just wondering if it was possible to implement the possibility of setting an alternative DNS provider rather than having to choose between the default ones. At least until the DoH protocol is natively implemented in GrapheneOS.

**Comment by csagan5** [comment]
I have changed the [wiki page](https://github.com/bromite/bromite/wiki/Enabling-DNS-over-HTTPS) to not suggest anything, note that in Bromite it has never been enabled by default anyways and my conclusion was/is that it is simply the best available option compared to the others (None, Google, Quad9, AdGuard).

This does not mean that I like Cloudflare, I really do not like their CDN for example but that doesn't mean that their DoH service has to be ditched in this case. I found it not to be particularly privacy-invasive (as much as any other, from what I could read in [their Privacy terms](https://developers.cloudflare.com/1.1.1.1/commitment-to-privacy/privacy-policy/privacy-policy/)).

Coincidentally yesterday I was considering the possibility to host a Bromite DoH endpoint, but it would never be as fast as a big company's one and I would not be able to ever make it scale for millions of users.

> I was just wondering if it was possible to implement the possibility of setting an alternative DNS provider rather than having to choose between the default ones.

I would love this feature :blush: however someone has to create the Android UI interface and code to allow this in the browser Settings, I am not that skilled unfortunately but I would never turn down a patch to add its support.

**Comment by paride15** [comment]
Thank you very much, you have been very kind. 
I think it's a good idea, you'd like to do something like Blahdns right? 
I hope this possibility will soon be implemented in Vinadium too.

**Comment by beerisgood** [comment]
You can use the Android internal DoT under "Network & Internet" -> "private DNS"

No need to use it only in the brower ;) 

Just enter the DoT server you want. If it doesn't work, Android tell you.

**Comment by thestinger** [comment]
I don't want to go out of the way to support this in Vanadium. GrapheneOS already supports DNS-over-TLS via the support for it in AOSP and I think it makes much more sense to implement DNS-over-HTTPS in the OS if it's wanted. Ultimately, I don't think it makes any sense for applications to provide their own DNS resolution, even if it's a browser. It should just use the OS DNS resolution and the OS should support encrypted DNS. It does have DoT already too.

**Comment by hmenke** [comment]
Google Chrome and Chromium (and therefore by extension also Vanadium) now support DNS-over-HTTPS with the Secure DNS feature.
https://support.google.com/chrome/answer/10468685?hl=en&co=GENIE.Platform%3DAndroid
Go to “Settings » Privacy and security » Use secure DNS” and turn it on. I'm not quite sure what the option “Use your current service provider” does. Selecting “Choose another provider” allows to select from a list: Cloudflare, OpenDSN, Google, NextDNS, CleanBrowsing, and *Custom*. However, even *Custom* still seems to have some kind of blocklist, because I was not able to use my own resolver.

**Comment by thestinger** [comment]
Why not use the secure DNS in the OS?

**Comment by buawf** [comment]
> Why not use the secure DNS in the OS?

  The Private DNS ?

**Comment by rusty-snake** [comment]
> However, even Custom still seems to have some kind of blocklist, because I was not able to use my own resolver.

To me it seems that it tries whether the provided URL supports DoH.

---

The downside of DoH in chromium is that it forgets your custom URL if you temporarily disable it (e.g. to open some intranet site).

Enabling DoT in Android on the other hand prevents you from resolving .local (mDNS, Avahi, ...) addresses.

**Comment by buawf** [comment]
> The downside of DoH in chromium is that it forgets your custom URL if you temporarily disable it (e.g. to open some intranet site).
> 
> Enabling DoT in Android on the other hand prevents you from resolving .local (mDNS, Avahi, ...) addresses.

  I'm currently using AdGuard's Private (not Public) DNS :-
     1.  System-wide Private DNS (DoT) has been set.
     2.  Plus, the same I've set into My Chrome browser (DoH).
     
  Anything wrong am I doing here ?

**Comment by rusty-snake** [comment]
1. Breaks `.local` as I said. Only relevant if you use them.
2. Seems to be redundant.

So I don't the something that is "wrong".

**Comment by buawf** [comment]
> 1. Breaks `.local` as I said. Only relevant if you use them.
> 2. Seems to be redundant.
> 
> So I don't the something that is "wrong".

  Thanks, God Bless You.
