### ISSUE TITLE
provide .apk builds

### ISSUE THREAD

**Issue by DI555** [GrapheneOS/Vanadium#51]
please, provide .apk builds in this repo 'releases' !
so, it will be possible to install Vanadium on usual android! ..and will be btw easy to update it on GrapheneOS!
as a result it gets more popularity to GrapheneOS!!!

**Comment by thestinger** [comment]
This can only be considered once https://github.com/GrapheneOS/Vanadium/issues/34 is resolved and the community has not been helping with it.

**Comment by thestinger** [comment]
A good example of why this can't happen, aside from a lot of the hardening for Vanadium being provided via GrapheneOS:

https://github.com/GrapheneOS/Vanadium/commit/c55efc40ad1938510ec7c237adc5b8b0653949aa
https://github.com/GrapheneOS/platform_frameworks_av/commit/7f7b234d7c05c3bdb304d886a317fd895e18021e

Videos are broken for 64-bit browser builds without this OS level workaround, and it's likely a bug in the OS. The next step is fixing the problem in the OS.

**Comment by muznyo** [comment]
> This can only be considered once https://github.com/GrapheneOS/Vanadium/issues/34 is resolved and the community has not been helping with it.

its resolved, is it possible now?

**Comment by thestinger** [comment]
We already provide Vanadium updates through our app repository.

**Comment by muznyo** [comment]
Are apks in github releases planned too?

**Comment by thestinger** [comment]
No. Our app repository can be used elsewhere but Vanadium isn't ready for use elsewhere.

**Comment by DI555** [comment]
what thing isn’t ready in Vanadium to be ready elsewhere ???

**Comment by rusty-snake** [comment]
From the README:

> It depends on hardening and compatibility fixes in GrapheneOS rather than reinventing the wheel inside Vanadium. For example, GrapheneOS already provides a hardened malloc implementation so there's no need for Vanadium to replace it.

Vanadium would therefore only be half as useful in other Android systems as it is in GrapheneOS.
