### ISSUE TITLE
Can't download via Vanadium

### ISSUE THREAD

**Issue by old-grey-wolf** [GrapheneOS/Vanadium#56]
Unable to download any files (tried pictures and apks) using Vanadium browser.

https://imgur.com/a/jnHVTiH
------------------------------------
"Vanadium needs storage access to download files."

->(Continue)

"Allow Vanadium to access photos and media on your device?"

->(Allow)

"Download file 7.22 MB

/FDroid.apk

/Downloads"

->(Download)

"SD card not found

Download to default folder?

/FDroid.apk

/Downloads"

->(Download)

Then this last popup just repeats.
------------------------------------

Reddit discussion : https://www.reddit.com/r/GrapheneOS/comments/f0zivr/cant_download_via_vanadium/

**Comment by njfox** [comment]
Upstream bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1045642

**Comment by jsrlabs** [comment]
I'm able to reproduce this bug on a fresh install of GrapheneOS QQ1A.200205.002.2020.02.07.19 on a Pixel 3. It is preventing any downloads.

**Comment by norbertc** [comment]
one workaround that worked for me is to allow bromite to install unknown apps. e.g. app info on bromite -> enable install unknown apps. it results in download error message in the notification but the file was really downloaded.

**Comment by countermeasure** [comment]
I can reproduce this on a fresh build on a Pixel 3a.

My fix is to go to Settings > Apps & notifications > Vanadium > Advanced > Install unknown apps, and flip the "Allow from this source" toggle to the on position.

**Comment by thestinger** [comment]
This has been resolved by backporting the upstream fix.

**Comment by thestinger** [comment]
The new release of Vanadium fixing this issue will be included in the *next* release of GrapheneOS.
