### ISSUE TITLE
Vanadium downloads PDFs but says download failed.

### ISSUE THREAD

**Issue by Damnedprinter** [GrapheneOS/Vanadium#59]
I am on a Pixel 3 build number QQ1A.200205.002.2020.02.07.19

When I download a PDF with Vanadium I get a notification that the download has failed. However when going into file manager, the file has actually been downloaded.

**Comment by thestinger** [comment]
Sounds like https://github.com/GrapheneOS/Vanadium/issues/56.

**Comment by Damnedprinter** [comment]
> Sounds like #56.

It is not like #56 at all. Vanadium says download failed but it actually succeeded

**Comment by thestinger** [comment]
Sounds like #56 to me either way. Read the upstream bug.
