### ISSUE TITLE
expand default search engines with more supposedly privacy-respecting options

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Vanadium#6]
Notice for people looking at this issue: **you can already add custom search engines and you do not need this feature to add search engines on your own**. This issue is about adding them to the built-in set of user-facing search engines. Many additional search engines are also **already** included in the built-in search engine database but aren't added to the curated per-locale list of search engines. The current curation is from upstream and based on measured traffic.

**Comment by csagan5** [comment]
Not meaning to influence your choice here, but so far I have excluded Searx (see https://github.com/bromite/bromite/issues/91) for accountability reasons, even if Brave decided to include it.

**Comment by thestinger** [comment]
This is not planned anymore at the moment since I wasn't really satisfied with the available options. For now, going with DuckDuckGo as the default, even though I find a lot of their marketing / announcements / posts misleading/dishonest.

**Comment by PacoBell** [comment]
Maybe reconsider that DDG decision.

https://www.bleepingcomputer.com/news/security/duckduckgo-browser-allows-microsoft-trackers-due-to-search-agreement/

**Comment by Zanthed** [comment]
We're already aware of DuckDuckGo not being a great option in the first place, but we'd rather not add things like random SearX or Startpage instances from random people.
