### ISSUE TITLE
get rid of the leftover Storage permission now that it isn't required

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Vanadium#64]
It still appears to be granted due to the app being bundled with the base system. It seems the legacy storage model might be granted even though it doesn't appear to be requested due to being bundled with the base system. It's also possible it has to do with upgrading from a legacy installation, so testing a fresh factory reset would be useful. In that case, it wouldn't be worth addressing this.

Android 11 should get rid of this once API 30 is targeted since it removes the legacy storage model.

**Comment by thestinger** [comment]
Need to test whether this is actually present on a fresh install. It's possible that it just got carried over from upgrading and isn't actually present for a fresh install. In that case, this issue should just be closed, especially since the permission will fully go away over time.

**Comment by refragable** [comment]
> Need to test whether this is actually present on a fresh install.

I flashed the official Graphene factory image on a Pixel 4 and Vanadium does not have the storage permission by default. I granted Vanadium the storage permission manually and storage permissions did not persist through a factory reset.

**Comment by thestinger** [comment]
This is not implemented yet since the change is breaking the build with Chromium 86.

**Comment by thestinger** [comment]
This is implemented now. I thought it was breaking the build but the problem seems to be something else.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/Vanadium/issues/90
