### ISSUE TITLE
Password saving / entering seems to have broken again

### ISSUE THREAD

**Issue by snrkl** [GrapheneOS/Vanadium#644]
Version 130.0.6723.86.0
app.vanadium.browser
versionCode 672308633
targetSdk 34
minSdk 29
Updated: 30 Oct 2024; 11:42
GrapheneOS: 2024103100

**Details:**
- Save password prompt not being offered (HTTP and HTTPS sites)
- Formerly saved passwords have dissapeared.

**Comment by snrkl** [comment]
Worth noting problem was noticed before today's updates, so don't assume the issue only started  in the version details listed above. 

Apologies for not having data on which version it broke in, I've been super busy and have not had the time to chase until today.

**Comment by snrkl** [comment]
![Screenshot_20241102-120832](https://github.com/user-attachments/assets/9c9a444e-ba91-4372-a2f3-6e9b27cff2fb)
I believe it is set to "on" correctly.

**Comment by snrkl** [comment]
This one?
![Screenshot_20241102-122215](https://github.com/user-attachments/assets/7c424527-7a55-4543-a023-ca57b7fe5244)

**Comment by snrkl** [comment]
Ok. That worked. Not sure what happened there settings wise. 

Thanks for that, and apologies for wasting time with a bug report for a config issue!!

**Comment by calhix** [comment]
Had a question about this, I have a password saved for a website within Vanadium but autofill using another service set so I can use a password manager for all other sites. Is it possible to implement a way to still prompt for a saved password or do you have another recommendation? I'm very excited for #659 and would like to not have to continually unlock the password manager to access a commonly used website I have added to the home screen. TIA!
