### ISSUE TITLE
Privacy-related: Consider enabling these two Chromium flags by default.

### ISSUE THREAD

**Issue by Peacock365** [GrapheneOS/Vanadium#71]
Please consider enabling _chrome://flags/#reduced-referrer-granularity_ and _chrome://flags/#prefetch-privacy-changes_ by default. The former is purely privacy-related, I don't know if you are already doing something similar. The latter prevents data leakage as described here:

https://terjanq.github.io/Bug-Bounty/Google/cache-attack-06jd2d2mz2r0/index.html

Here is the "Intent to implement" in Chromium:

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/bSMOY-evrV4

I have raised the same issue in the Brave browser repo, with the result that the flags got enabled by default:

https://github.com/brave/brave-browser/issues/8319

Thank you for your attention.

**Comment by Peacock365** [comment]
Update on the issue: Ungoogled Chromium and Bromite have enabled these flags by default now.

**Comment by thestinger** [comment]
https://www.chromestatus.com/feature/6251880185331712

The referrer policy change is enabled by default since Chromium 85.

**Comment by thestinger** [comment]
This is implemented.
