### ISSUE TITLE
Global auto-fill service doesn't trigger

### ISSUE THREAD

**Issue by Son-Of-Enki** [GrapheneOS/Vanadium#76]
I'm sorry if this isnt the correct format or place to post this. I am new to git hub and all I can do is describe the problem. The global autofill for my password manager(Bitwarden) doesn't trigger in Vanadium on GrapheneOS. This is annoying because I either have to copy and paste from Bitwarden, type in username and password manually, or save the username and password insecurely in the browser's native autofill. I also experienced this same issue in Bromite browser on Android 10, so maybe this is a problem across all Chromium based browsers, but I haven't used any non-foss browsers in quite some time, so I have nothing to compare to. The global auto fill service and auto fill accessibility service are activated in the system settings, and it works for all other apps including other web browsers such as Firefox Klar.

**Comment by foosroos** [comment]
I do not have issues in base Vanadium with Bitwarden. I'm not exactly sure what is the difference between our setups, though.

On a very similar note, I am finding it to be an issue with PWAs made using the browser. I'm not sure if that's a feature of Vanadium hardening or not.

**Comment by csagan5** [comment]
My conclusion on this topic is here: https://github.com/Kunzisoft/KeePassDX/issues/551#issuecomment-647768275

**Comment by foosroos** [comment]
Thanks for the link, csagan5. Any ideas then why I'm able to use the autofill service in the base chromium browsers? I gave Bromite a try and it functions like Vanadium, currently.

**Comment by thestinger** [comment]
> or save the username and password insecurely in the browser's native autofill

What makes you think that's insecure?

**Comment by csagan5** [comment]
@foosroos it is explained in that comment.

**Comment by mmfire118** [comment]
It seems Bromite fixed this issue: https://github.com/bromite/bromite/issues/547 

Could it be added to Vanadium?

**Comment by Zanthed** [comment]
#132

**Comment by CrashenX** [comment]
@quh4gko8 Curious why #132 stalled. Is the approach invalid or a better alternative path forward?

**Comment by dd-dreams** [comment]
@quh4gko8 so native autofill will always be enabled, or a toggle in a different way?

**Comment by thestinger** [comment]
Replacing with https://github.com/GrapheneOS/Vanadium/issues/276.
