### ISSUE TITLE
Unable to build Vanadium for Pixel 3aXL PQ3B.190801.002.2019.08.25.15

### ISSUE THREAD

**Issue by cabahug2** [GrapheneOS/Vanadium#79]
Hello!

I'm trying to build GrapheneOS for Pixel 3aXL using the last Android 9 build (PQ3B.190801.002.2019.08.25.15). I'm at the point where I'm trying to build the prebuilts and copy them into the Android tree. I've tried to build the trichrome modules using `ninja -C out/Default/ trichrome_webview_apk trichrome_chrome_bundle trichrome_library_apk`, however I'm getting an error due to an undefined string resource

`../../chrome/android/features/vr/java/src/org/chromium/chrome/browser/vr/VrShell.java:1107: error: cannot find symbol
        mActivity.onMenuOrKeyboardAction(R.id.help_id, true);`

**Comment by thestinger** [comment]
You shouldn't be using Android 9 tags from over a year ago. Use the tag from the last stable release or wait until the upcoming tag for the stable Android 11 release in the next couple days.

**Comment by thestinger** [comment]
Only building the most recent stable release is supported. Trichrome is only for Android 10 and later anyway. It won't work on Android 9. Just build either the current development branch or wait for the next stable tag which should match exactly what's in the current `11` branch right now.
