### ISSUE TITLE
Vanadium intermitently opens in offline mode

### ISSUE THREAD

**Issue by TechyKeith** [GrapheneOS/Vanadium#80]
Vanadium opens in offline mode, usually when selecting a site I have bookmarked, it is hard to reproduce as it is intermittent, probably occurs 30% of the time I use vanadium. 

Mainly from bookmarked pages
Has only started occurring since android 11 upgrade, was apparent immediately after the upgrade, never happened on android 10 (have been running GOS as daily driver for over 6 months)
Google pixel 3 xl

when this occurs opening a new tab resolves it and close the offline tab 
I have never used offline mode or chosen to work offline in vanadium. 

I love this project and hope this can help.

**Comment by thestinger** [comment]
You appear to have a connection that's not reliable. You should look into your network settings in particular whatever you might have changed from the defaults. VPN, DNS server, etc. You need to look into which networks this occurs on. It's not an issue with Vanadium but rather Vanadium is detecting that the network is not functioning properly as part of the standard functionality for that. The OS probably detects the same thing and marks the connection as not having internet access temporarily.
