### ISSUE TITLE
Request "Desktop" Site - User Agent being flagged as "mobile"

### ISSUE THREAD

**Issue by mickotronic** [GrapheneOS/Vanadium#83]
When I request "Desktop Site" from within Vanadium (and in Chrome), some sites do not register the User Agent to be a Desktop, and serve the mobile site instead.

Example: Deezer.com
Tested whether requesting Desktop mode serves the desktop page:
**[FAIL]** Google Pixel 3a (GrapheneOS), Vanadium 85.0.4183.127, Android 11
**[PASS]** Google Pixel 3a (GrapheneOS), Fennec 81.1.5
**[FAIL]** Google Pixel 2 (stock), Chrome 86.0.4240.99, Android 11
**[PASS]** Google Pixel 2 (stock), Firefox 81.1.4, Android 11
**[FAIL]** Desktop, Solus Linux, Chrome 81.0.4044.113
**[PASS]** Desktop, Solus Linux, Firefox 81.0

I use the Deezer music streaming web app instead of the app. I can download it from Aurora store on my GrapheneOS Pixel, but I don't want the trackers (https://reports.exodus-privacy.eu.org/en/reports/deezer.android.app/latest/).

Recently the website keeps redirecting me to their "offers" page after login, instead of the web app. This only happens on mobile. The old workaround was to request the "Desktop" site within Vanadium. However, this recently has stopped working.

I have raised this with Deezer themselves, specifically to the javascript they serve that causes this issue. However, the issue seems to be related to Chrome/Chromium, as it may use different User Agent(s) than Firefox when requesting the Desktop site. That might explain the difference between Chrome/Firefox test results above?

When testing on Desktop, using Developer Tools in Chrome to change the User Agent, I was able reproduce the issue. When I selected "mobile" User Agents, the page would redirect to the "offers" page, while "Desktop" User Agents gave me the Desktop site.

**Comment by thestinger** [comment]
Definitely a problem with the site, not Vanadium. Chrome is by far the most used mobile browser.

**Comment by thestinger** [comment]
> but I don't want the trackers

Apps don't need third party SDKs to track usage of the app and I'm sure their website also does it. That report is highly misleading since it's just detecting third party SDKs for analytics. Apps include their own analytics too. Only major SDKs are listed there. It's misleading information. Also, what exactly do you think it means? I'd suggest reading about how the application model works including the app sandbox and permission model.

**Comment by mickotronic** [comment]
Hi Daniel,

Thanks for the reply.

I admit I do need to read up on android app sandbox and permission model. Would you agree/disagree that there would be less tracking while using a website with vanadium and blokada, for instance, vs using the app?

I am in the process of determining the logic in their JavaScript that flags me as being on mobile, with the hopes this knowledge can assist me to work around it and access their desktop site.

I have yet to hear back from Deezer since requesting to speak with their development team.

Regards,

Mike

**Comment by thestinger** [comment]
Tracking of what exactly?

**Comment by mickotronic** [comment]
Data other than what is required to run the service, such as personally identifiable information, and information not related to the service itself. I guess my assumption was that if the app is running on the device it would have much greater ability to track in greater detail. Is that an incorrect assumption?

If you are saying there is negligible difference between using their web app in vandadium, vs using their native android app (re tracking, capabilities) then I might as well download the app? Just wondering whether my assumption is wrong and I should avoid the hassle of trying to get the web app to render.

**Comment by thestinger** [comment]
There's a lot more attack surface for an app but if you revoke Sensors and don't grant it access to other things, it's not like it can obtain personal information. It's not clear what you mean by tracking. A web app can track your usage of the software just as easily and that's what nearly all these tracking SDKs are doing.

**Comment by mickotronic** [comment]
I guess my biggest concerns are:
1. Limiting attack surface - reduce apps installed.
2. Limiting data sent to third parties/advertising companies while using services (especially those I pay for). This is somewhat unavoidable entirely but as I said, I want to limit any data collection where possible. I don't like the idea there is an entire economy around buying/selling my data, whether its in aggregate or raw form, and I don't entirely know what data is being collected, when, who is getting access to it, how is it stored, etc etc. Besides I don't like the premise that we must opt in to widespread and in some cases arbitrary data collection because we want to use a paid for service.</endrant>
