### ISSUE TITLE
Opening links in external apps doesn't work

### ISSUE THREAD

**Issue by Wonderfall** [GrapheneOS/Vanadium#84]
**Informations**
OS: GrapheneOS 11 (2020.10.23.04)
Device: Pixel 3a
Browser: Vanadium 86.0.4240.99

**Expected behavior**
Opening a supported link should ask if an app is available.

**Current behavior**
Vanadium doesn't ask and opens the link itself.

**Replication**
Affected browsers: Vanadium 86.0.4240.99, Bromite 86.0.4240.112
Non-affected: Chrome 86.0.4240.110, Bromite 85.0.4183.114
On: new profile, default settings

**Comment by thestinger** [comment]
Can you try Chrome 86.0.4240.99 from apkmirror?

**Comment by thestinger** [comment]
Can you also try Vanadium 85.0.4183.114 from https://github.com/GrapheneOS/platform_external_vanadium?

**Comment by thestinger** [comment]
Install all three of these as updates to it:

https://github.com/GrapheneOS/platform_external_vanadium/tree/11/prebuilt/arm64

**Comment by Wonderfall** [comment]
> Can you also try Vanadium 85.0.4183.114 from https://github.com/GrapheneOS/platform_external_vanadium?

Working.



> Install all three of these as updates to it:
> 
> https://github.com/GrapheneOS/platform_external_vanadium/tree/11/prebuilt/arm64

Installed and not working.

**Comment by thestinger** [comment]
I don't really see what we could be changing related to this that would be breaking it.

**Comment by thestinger** [comment]
Maybe @csagan5 knows more since it stopped being an issue for Bromite.

**Comment by Wonderfall** [comment]
In fact it still affects Bromite, it just didn't affect `85.0.4183.114` (85). Latest Bromite is also affected.
Very strange indeed.

**Comment by Wonderfall** [comment]
I didn't read correctly your previous message, should I have installed Vanadium 85.0.4183.114 instead? I'm running 86.0.4240.114 right now.

**Comment by thestinger** [comment]
> In fact it still affects Bromite, it just didn't affect 85.0.4183.114 (85). Latest Bromite is also affected.

It sounds like this is a Chromium issue introduced in v86 so that makes sense. I misread the 85.0.4183.114 version as 86.

**Comment by thestinger** [comment]
> I didn't read correctly your previous message, should I have installed Vanadium 85.0.4183.114 instead? I'm running 86.0.4240.114 right now.

You can't install downgrades to apps.

**Comment by Wonderfall** [comment]
> > I didn't read correctly your previous message, should I have installed Vanadium 85.0.4183.114 instead? I'm running 86.0.4240.114 right now.
> 
> You can't install downgrades to apps.

Yes I figured, there was some confusion.

I'm still available if you need testing, in the meantime I'm gonna check the Chromium issue tracker for something related.

**Comment by thestinger** [comment]
Marking it as upstream since that seems likely due to the lack of any apparent relevant changes and the issue impacting Bromite too.

**Comment by Wonderfall** [comment]
> Marking it as upstream since that seems likely due to the lack of any apparent relevant changes and the issue impacting Bromite too.

Very likely. A friend of mine just replicated this issue on latest Bromite + OEM Android.

**Comment by thestinger** [comment]
Have you done any testing on Android 10?

**Comment by Wonderfall** [comment]
> Have you done any testing on Android 10?

Yes, my friend is on Android 10.

**Comment by thestinger** [comment]
Fixed by backporting https://github.com/chromium/chromium/commit/cdc6f38e3e4a994df8c40c6f0b4b7db14da2dd35. It was an upstream bug.

**Comment by csagan5** [comment]
Related: https://github.com/bromite/bromite/pull/816
