### ISSUE TITLE
provide dictionary downloads via GrapheneOS server or bundle them

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Vanadium#88]

**Comment by csagan5** [comment]
What dictionary are these? Wondering if it is covered in Bromite or needs a patch also there.

**Comment by thestinger** [comment]
You've disabled updating the list of available dictionaries but I still think it will attempt (and fail, due to domain replacement) to obtain the dictionaries from the gvt1 redirector URL.

https://github.com/bromite/bromite/blob/master/build/patches/translate-disable-fetching-of-translate-languages-from-server.patch

**Comment by thestinger** [comment]
i.e. go to languages and add a language

**Comment by thestinger** [comment]
https://github.com/chromium/chromium/blob/301d265e779c792a4e050dbdd795e24eb46158d9/chrome/browser/spellchecker/spellcheck_hunspell_dictionary.cc#L259

**Comment by csagan5** [comment]
I just tested with Wireshark, I see no requests made when adding a language. I wonder how this is supposed to work.

**Comment by thestinger** [comment]
This is done.
