### ISSUE TITLE
WebView Default Browser Issue

### ISSUE THREAD

**Issue by linuxhelper** [GrapheneOS/Vanadium#91]
Hi, sorry in advance if this is the wrong place to post. I'm having issues with WebView on my Pixel 4A with GrapheneOS (Stable RQ1A.201205.008.2020.12.08.08). Feeder, my RSS app, is unable to display news articles inside the app with the WebView button when the default browser is switched from Vanadium to Bromite. I'm not sure why—I was under the impression WebView was managed by Vanadium regardless.

YouTube [Video](https://youtu.be/VJ1gVMxhTCg) — Thanks :)!!

**Comment by beerisgood** [comment]
You can't change the webview browser. What's why your app doesn't work.

**Comment by thestinger** [comment]
This isn't related to the WebView. That's not the WebView in that app but rather the custom tab API. It's quite possible that Bromite disables the feature.

**Comment by linuxhelper** [comment]
I'm not sure I understand. The tab says, "Open in web view" when I long press it.

> This isn't related to the WebView. That's not the WebView in that app but rather the custom tab API. It's quite possible that Bromite disables the feature.

![Screenshot_20201213-132305](https://user-images.githubusercontent.com/50037005/102024355-623b7180-3d46-11eb-961b-01ed21f7280b.png)

WebView is separate from my understanding.

> You can't change the webview browser. What's [sic] why your app doesn't work.

Maybe Feeder isn't "most other apps".

> <b>Vanadium:</b> hardened WebView and default browser - the WebView is what most other apps use to handle web content, so <b>you benefit from Vanadium in many apps even if you choose another browser.</b>
https://grapheneos.org/features

Thanks for the replies!! Maybe I will find an alternative app or shoot the developer of Feeder a message. I'm not even sure what other app to use that would reproduce a WebView related issue.

Tab APIs and WebView are way over my head. Loving GrapheneOS :)

**Comment by thestinger** [comment]
> I'm not sure I understand. The tab says, "Open in web view" when I long press it.

The app has an inaccurate label. It probably wasn't updated when they added support for Chrome custom tabs. They might be using a library abstracting it and they don't actually know how it works.

> WebView is separate from my understanding.

The app isn't opening it in the WebView. My response above is accurate. It's opening it with the browser. Bromite probably disabled custom tab support, so it doesn't open in a custom tab but rather the browser itself.

> Maybe Feeder isn't "most other apps".
>
> Thanks for the replies!! Maybe I will find an alternative app or shoot the developer of Feeder a message. I'm not even sure what other app to use that would reproduce a WebView related issue.

It's not rendering content in a WebView.

> Tab APIs and WebView are way over my head. Loving GrapheneOS :)

Please listen to the official developer response here then.

**Comment by thestinger** [comment]
Bromite makes it so that custom tabs require enabling a toggle:

https://github.com/bromite/bromite/blob/master/build/patches/Add-custom-tab-intents-privacy-option.patch

This is essentially a question about Bromite. You're confused because the app mislabels this feature as using the WebView. It doesn't mean it's true. It's not what it is doing.
