### ISSUE TITLE
User-installed certificates are permitted by default

### ISSUE THREAD

**Issue by Flex1911** [GrapheneOS/Vanadium#96]
Current Android policy allows user-installed certificates usage only if that specific certificate is permitted by the specific application in its network security config. 
Default Chrome configuration though allows all user-installed certificates, potentially making it easier to let in the malicious traffic.

This is just a proposal, so I would understand if the whole situation is not an issue for GrapheneOS/Vanadium and is only a problem for my specific usecase.

PR: https://github.com/GrapheneOS/Vanadium/pull/95

**Comment by ypid** [comment]
I am not sure what the threat model is and if it outweighs the disadvantages. Installing user certificate already (Android 11) give you a big warning and requires you to authenticate against the device.

I run my own CA and would like to continue using services using this CA via web.

**Comment by thestinger** [comment]
I don't think we want to *outright* remove support for this rather than showing a warning. I think I'd rather leave this as is for the time being.
