### ISSUE TITLE
search engine notifications are overly disabled

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Vanadium#99]

**Comment by thestinger** [comment]
No longer going to be an issue due to upstream implementation of the feature we were making downstream.

**Comment by csagan5** [comment]
Which feature is it? Just curious

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/Vanadium/blob/11/patches/0052-disable-search-engine-permissions-by-default.patch is the new patch enabling the upstream feature.
